### ISSUE TITLE
make && make install error

### ISSUE THREAD

**Issue by yuluhan** [NVIDIA/VideoProcessingFramework#94] opened 2020-08-18 03:07 UTC
Hi, I encounter the error bellow, I've try CUDA10.0, 10.1 and 10.2 but still get the same error result.
the solution from issue #54 does not work for me.
![make_error](https://user-images.githubusercontent.com/59047015/90465294-a96f7800-e141-11ea-9120-3471fad0552e.png)

ffmpeg version, which is compiled as the wiki shows 
![ffmpeg](https://user-images.githubusercontent.com/59047015/90465743-990bcd00-e142-11ea-904f-81be7c43d9c2.png)

OS: Ubuntu 16.04
Nvidia driver version: 450.57
CUDA Version  10.1
Video Codec SDK Version  10.0.26
Python Version [conda env 3.6]

**Comment by rarzumanyan** [comment] 2020-08-18 10:41
Hi @yuluhan 

This is duplicate of https://github.com/NVIDIA/VideoProcessingFramework/issues/89

**Closed by rarzumanyan** 2020-08-18 10:41 UTC
