### ISSUE TITLE
Feature request: return metadata (PTS) with frames

### ISSUE THREAD

**Issue by riaqn** [NVIDIA/VideoProcessingFramework#253] opened 2021-10-01 10:41 UTC
As the title suggests, I hope the decoding API could provide the PTS (and other metadata) of frames. For example,  `DecodeSurfaceFromPacket` should return the decoded surface AND metadata. It's suggested to be easy to do: https://github.com/NVIDIA/VideoProcessingFramework/issues/28#issuecomment-932080769

**Comment by rarzumanyan** [comment] 2021-10-01 10:59
Please check out `issue_253` branch, it adds `PacketData` reference as argument to `DecodeFrameFromPacket` and `DecodeSurfaceFromPacket` functions.

If feature works as expected - LMK, I'll merge it to `master` branch.

**Comment by riaqn** [comment] 2021-10-01 11:15
Thanks for the super quick patch! It might take a while for me to try - but I will let you know!

**Comment by riaqn** [comment] 2021-10-01 13:34
I might be missing something - after using the issue_253 branch, and modify `decode_frame_standalone` in `SampleDecode.py`
```
            frame_ready = self.nv_dec.DecodeFrameFromPacket(self.frame_nv12, self.packet, self.packet_data)
```
But the printed `self.packet_data` is still out-of-order in PTS. Is this `packet_data` simply derived from the `self.packet` in the same call? It might not correspond to the `surface` returned due to B-frames?

I guess I didn't specify my need right - I hope to acquire the PTS of the surface/frame.

**Comment by rarzumanyan** [comment] 2021-10-01 13:48
The reason for that is probably as follows:

When built-in demuxer is used, encoded packet data is passed to decoder alongside Annex.B bitstream (line 720):
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/PyNvCodec/src/PyNvCodec.cpp#L707-L729

And then this data is passed to decoding task which takes encoded packet pts (line 307):
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/PyNvCodec/TC/src/Tasks.cpp#L304-L309

As it goes down the call stack, pts is passed to Video Codec SDK API here (line 679):
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/PyNvCodec/TC/src/NvDecoder.cpp#L674-L683

Because Nvdec outputs frames in display order, we need to store pts in VC SDK API structures to avoid frames confusion due to reordering.

So to resolve the issues you're seeing one additional modification shall be done to `DecodeFrameFromPacket` and `DecodeSurfaceFromPacket` functions - they shall accept packet's `PacketData` structure as well.

**Comment by riaqn** [comment] 2021-10-01 13:54
Thanks for the quick response - I look forward to it. BTW, is it possible to have the same enhancement for `FlushSingleSurface`? It returns a surface and I hope to obtain the PTS of that surface.

**Comment by riaqn** [comment] 2021-10-01 15:42
Another thing: my program SIGSEGV in the following `DecodeSurfaceFromPacket`. `packet` is from PyAV demuxer. I assume that's what you were talking about? (bitstream filter and Annex.B elementary bitstream [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/99). 
```
            print(f'len(packet) = {packet.buffer_size}')
            arr = np.frombuffer(packet.to_bytes(), dtype=np.uint8)
            print(f'len(arr) = {arr.shape}')
            print('hello 1')
            packetData = nvc.PacketData()            
            print('hello 2')
            surface = self.nvDec.DecodeSurfaceFromPacket(arr)
            print('hello 3')
            if not surface.Empty():
                yield (packetData, surface)
            print('hello 4')
```

**Comment by rarzumanyan** [comment] 2021-10-01 15:48
>I assume that's what you were talking about?

Yes. 
You can't just use pointer to `AVPacket` data, you need to extract Annex.B bitstream from video first which is done with the help of bitstream filters. Unfortunately, to my best knowledge, feature branch with bitstream filters was never merged to main.

**Comment by riaqn** [comment] 2021-10-01 15:56
> > I assume that's what you were talking about?
> 
> Yes. You can't just use pointer to `AVPacket` data, you need to extract Annex.B bitstream from video first which is done with the help of bitstream filters. Unfortunately, to my best knowledge, feature branch with bitstream filters was never merged to main.

Yes the related issue is here and it's still not merged, and the authors didn't tell us what's blocking...

**Comment by rarzumanyan** [comment] 2021-10-03 16:43
I've pushed a patch which adds incoming packet data support to `issue_253` feature branch, please check it out.

**Comment by riaqn** [comment] 2021-10-03 16:49
Thanks! The compilation succedd but I got the following error:
```
  File "/root/decode.py", line 2, in <module>
    import PyNvCodec as nvc
ImportError: /usr/lib/python3.9/site-packages/PyNvCodec.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN11PyNvDecoder21DecodeFrameFromPacketERN8pybind117array_tIhLi16EEER10PacketDataS3_S5_
```

**Comment by riaqn** [comment] 2021-10-04 05:13
I'm looking at the patch, and it seems like four new `DecodingFrameFromPacket` declarations are added, but none are actually defined?

**Comment by rarzumanyan** [comment] 2021-10-04 08:37
Hi @riaqn 

Yes, some implementations were missing indeed. I've added them, check out `issue_253` ToT.

**Comment by riaqn** [comment] 2021-10-04 08:49
@rarzumanyan Thanks! But now the definition of `FlushSingleFrame` is missing :smile_cat: 
I know we've been through this, but a lot of the duplicative code because of different signatures can be avoided if they are written in Python... It's your call after all. :smile:

**Comment by rarzumanyan** [comment] 2021-10-04 08:56
Hi @riaqn 

>I wonder if lot of the duplicative code because of different signatures can be avoided if they are written in Python

They can be. I don' have a chance to take this task up - please take it up if you can. 
Otherwise I don't think it would helpful to go on with this discussion in purely theoretical manner.

Please check up `issue_253` ToT, I've added missing implementations.

**Comment by riaqn** [comment] 2021-10-04 09:18
> They can be. I don' have a chance to take this task up - please take it up if you can.
Sure - I understand.

The import works now - I will try the program later and let you know!

**Comment by riaqn** [comment] 2021-10-04 16:49
@rarzumanyan Hi I get to try my program:
```
for packet in packets:
            pd = nvc.PacketData()
            surface = self.nvDec.DecodeSurfaceFromPacket(packet, pd)
            if not surface.Empty():
                print(pd.pts, pd.dts)
```
But all it prints are zeros - seems like `pd` is not modified at all? (`packets` are given by `PyFFmpegDemuxer`)

**Comment by rarzumanyan** [comment] 2021-10-04 17:07
```python
pd = nvc.PacketData()
surface = self.nvDec.DecodeSurfaceFromPacket(packet, pd)
if not surface.Empty():
    print(pd.pts, pd.dts)
```

You're not providing `PyNvDecoder` with any information about incoming compressed video frame, hence it doesn't return anything. Also, what's the nature of the `packet`? It shall be `uint8` `numpy.ndarray` with Annex.B NALu.
I assume your code shall look like this:

```python
pd_in = nvc.PacketData()
pd_in.pts = pts
pd_in.dts = dts

pd_out = nvc.PacketData()

surface = self.nvDec.DecodeSurfaceFromPacket(pd_in, packet, pd_out)

if not surface.Empty():
    print(pd_out.pts, pd_out.dts)
```

PTS and DTS aren't essential parts of Annex.B NALu hence Nvdec doesn't need them to restore pixels. Hence you need to provide decoder with PTS and DTS information. When `PyNvDecoder` is used in standalone mode, this is done in C++ land as I've shown you before.

**Comment by riaqn** [comment] 2021-10-04 17:44
Thank you - that clear things up, this is my current code:
```
def decode(self, packets):
        pd_out = nvc.PacketData()        
        for pd_in, packet in packets:
            print(f"in: PTS={pd_in.pts} DTS={pd_in.dts}")
            # packetData = nvc.PacketData()
            surface = self.nvDec.DecodeSurfaceFromPacket(pd_in, packet, pd_out)
            if not surface.Empty():
                print(f'out: PTS={pd_out.pts} DTS={pd_out.dts}')
                yield (pd_out, surface)
```
`pd_in` is given by `PyFFmpegDemuxer.LastPacketData`. When run this, I get:
```
in: PTS=229000 DTS=229000
out: PTS=0 DTS=0
in: PTS=231000 DTS=230000
out: PTS=0 DTS=0
in: PTS=236000 DTS=231000
out: PTS=0 DTS=0
in: PTS=234000 DTS=232000
out: PTS=0 DTS=0
in: PTS=233000 DTS=233000
out: PTS=0 DTS=0
in: PTS=235000 DTS=234000
out: PTS=0 DTS=0
in: PTS=239000 DTS=235000
```
seems like `pd_in` is working as intended, but `pd_out` is not modified.

**Comment by rarzumanyan** [comment] 2021-10-05 10:47
Hi @riaqn 

That was caused by one nasty little bug making `Buffer` allocation of wrong size:
```cpp
Buffer::MakeOwnMem(sizeof(*p_packet_data, p_packet_data)));
```
Closing bracket was put in wrong place and as it usually happens it didn't break the proper syntax but broke everything else.
Please check out `issue_253` branch. I've run some tests on my machine, now `PacketData` is properly updated by `PyNvDecoder`.

**Comment by riaqn** [comment] 2021-10-05 11:08
@rarzumanyan Thanks! I just tested and it works as intended - Very much appreciated!

**Comment by riaqn** [comment] 2021-10-05 11:39
Another thing: currently it seems that only the `pts` field is modified? I think some applications could make use other fields as well (such as duration) - could you please add that? :smile:

**Comment by rarzumanyan** [comment] 2021-10-05 11:53
Nvdec returns reconstructed frames in presentation (display) order, hence it only returns PTS which is presentation timestamp.

Such feature addition is going to be labor intensive (because it's not supported in Video Codec SDK API) and will require some design changes in `PyNvDecoder` class. One will have to implement incoming and outgoing packets queue. 

I will probably take this up in the future as next re-factoring round occurs but not anytime soon.

P. S.
As the requested feature is implemented and working I'm closing this issue as resolved and merge it to `master` branch.

P. P. S.
If you're using VPF commercially and this feature is required for your project, please contact me via email (in description). Incoming customer request may help justify additional time I spend on VPF which is my side project.

**Closed by rarzumanyan** 2021-10-05 11:53 UTC

**Comment by riaqn** [comment] 2021-10-05 12:33
> Such feature addition is going to be labor intensive (because it's not supported in Video Codec SDK API) and will require some design changes in PyNvDecoder class. One will have to implement incoming and outgoing packets queue.

Yeah I'm not in a rush - looking forward to it.

> If you're using VPF commercially and this feature is required for your project, please contact me via email (in description). Incoming customer request may help justify additional time I spend on VPF which is my side project.

I'm only using it for my hobby project. However, maybe you can provide some link so we small users can buy you a cup of coffee? :smile:

**Comment by rarzumanyan** [comment] 2021-11-01 11:36
Hi @riaqn 

Please take a look at `master` ToT, after some refactoring, `PyNvDecoder` now saves incoming `PacketData` information in queue and returns it when frame is decoded. So decoder now returns you not only pts, but everything demuxer gives it.

You can see this in latest `SampleDemuxDecode.py`.

**Comment by riaqn** [comment] 2021-11-02 08:45
@rarzumanyan Thanks a lot! I just tested it and it works perfectly. :+1:

**Comment by riaqn** [comment] 2021-11-06 12:04
@rarzumanyan I'm seeing some error message 
```
Incoming packet with pts 0 already exists in the queue
```
Looking at the code, I believe this is caused by https://github.com/NVIDIA/VideoProcessingFramework/blob/9a1801ffab465a271e32537a775720c9f3b6dfeb/PyNvCodec/TC/src/NvDecoder.cpp#L742

To ensure that my code is right, I add
```
        assert pts != 0
```
before passing to `DecodeSurfaceFromPacket`. I still get the same error. Could you look at this please?

**Comment by rarzumanyan** [comment] 2021-11-06 12:30
@riaqn 

It's under conditional compilation flag:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9a1801ffab465a271e32537a775720c9f3b6dfeb/PyNvCodec/TC/src/NvDecoder.cpp#L741-L744

This section shall not be even compiled.

**Comment by riaqn** [comment] 2021-11-06 12:31
@rarzumanyan Yes it's under conditional compilation in the latest commit - I will just update. Do you mean I can just ignore this warning?

**Comment by rarzumanyan** [comment] 2021-11-06 12:34
Yes, they pop up when queue of `PacketData`  structures is filled with garbage data from demuxer.

This may happen e. g. when you use external demuxer and feed Nvdec with Annex.B only, hence it doesn't know anything about the pts, duration and such.

**Comment by riaqn** [comment] 2021-11-06 12:36
Thanks! That clear things up. Sorry about the noise. :smile:

**Comment by rarzumanyan** [comment] 2021-11-06 12:38
Absolutely NP.

That's actually something I've messed up with when I was merging feature branch to `master`.
Stderr was suppressed in my tests and I didn't see these noisy messages. This is how they end up being in `master`.
