### ISSUE TITLE
Decoding fake stream

### ISSUE THREAD

**Issue by pdd-999** [NVIDIA/VideoProcessingFramework#316] opened 2022-03-29 05:14 UTC
**Describe the bug**
VPF can't decode a generated rtsp stream. The surface is always empty. I will refer to this rtsp stream as a "fake" stream for now.

**To Reproduce**

1. Build the docker image and start with addtional config in `docker-compose.yml`: `network_mode: host`.

2. Create fake stream:
- Install and run [simple rtsp server](https://github.com/aler9/rtsp-simple-server).
- Prepare a test video and create the fake stream with ffmpeg:
```
ffmpeg -re -stream_loop -1 -i test_video.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/live.sdp
```
3. My testing script:
```
import time
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from threading import Thread

import cv2
import numpy as np
import PyNvCodec as nvc
import torch
import PytorchNvCodec as pnvc
from loguru import logger

def decode_thread(gpuID, encFilePath, output_deque):
    nvDmx = nvc.PyFFmpegDemuxer(encFilePath, {'rtsp_transport': 'tcp'})
    nvDec = nvc.PyNvDecoder(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvDmx.Codec(), gpuID, )

    packet = np.ndarray(shape=(0), dtype=np.uint8)
    pdata_in, pdata_out = nvc.PacketData(), nvc.PacketData()
    width = nvDmx.Width()
    height = nvDmx.Height()
    format = nvDmx.Format()
    codec = nvDmx.Codec()

    cspace, crange = nvDmx.ColorSpace(), nvDmx.ColorRange()
    if nvc.ColorSpace.UNSPEC == cspace:
        cspace = nvc.ColorSpace.BT_601
    if nvc.ColorRange.UDEF == crange:
        crange = nvc.ColorRange.MPEG
    cc_ctx = nvc.ColorspaceConversionContext(cspace, crange)

    if cspace != nvc.ColorSpace.BT_709:
        nvCvt = nvc.PySurfaceConverter(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvc.PixelFormat.YUV420, gpuID)
        nvCvt_RGB = nvc.PySurfaceConverter(nvDmx.Width(), nvDmx.Height(), nvc.PixelFormat.YUV420, nvc.PixelFormat.RGB, gpuID)
    else:
        nvCvt = None
        nvCvt_RGB = nvc.PySurfaceConverter(nvDmx.Width(), nvDmx.Height(), nvDmx.Format(), nvc.PixelFormat.RGB, gpuID)

    while True:
        if not nvDmx.DemuxSinglePacket(packet):
            break

        try:
            nvDmx.LastPacketData(pdata_in)
            surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)
        except Exception as e:
            import traceback
            logger.error(f"Error decoding frame {traceback.format_exc()}")
            logger.info(f"Reset HW")
            nvDec = nvc.PyNvDecoder(width, height, format, codec, gpuID)
            continue

        if not surface_nv12.Empty():
            if nvCvt is not None:
                surface_yuv420 = nvCvt.Execute(surface_nv12, cc_ctx)
                if surface_yuv420.Empty():
                    break
                cvtSurface = nvCvt_RGB.Execute(surface_yuv420, cc_ctx)
            else:
                cvtSurface = nvCvt_RGB.Execute(surface_nv12, cc_ctx)

            surf_plane = cvtSurface.PlanePtr()
            surface_tensor = pnvc.makefromDevicePtrUint8(surf_plane.GpuMem(),
                                                    surf_plane.Width(),
                                                    surf_plane.Height(),
                                                    surf_plane.Pitch(),
                                                    surf_plane.ElemSize())
            surface_tensor.resize_(height, width, 3)
            output_deque.appendleft(surface_tensor)
        else:
            logger.error(f"Surface is empty")

def decode(gpuID, encFilePath, camID, fps=20):
    output_deque = deque(maxlen=1)
    vpf_thread = Thread(target=decode_thread, args=(gpuID, encFilePath, output_deque))
    vpf_thread.start()
    
    while True:
        st = time.time()
        try:
            frame = output_deque.pop()
        except IndexError:
            took = time.time() - st
            left = 1/fps-took
            if left > 0:
                time.sleep(left)
            continue
        frame = frame.flip(-1)
        frame = frame.cpu().numpy()
        cv2.imwrite(f"test_{camID}.jpg", frame)

if __name__ == "__main__":
    gpuID = 0
    encFilePath = "rtsp://192.168.40.5:8554/live.sdp"
    
    pool = ThreadPoolExecutor(max_workers=4)
    with pool:
        for idx in range(4):
            pool.submit(decode, gpuID, encFilePath, idx)

    logger.info(f"All clean")

```

**Expected behavior**
The script should run normally and an image name `test.jpg` should be saved in the same directory.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04.3 LTS)
 - Nvidia driver version: 460.84
 - CUDA Version: 11.2
 - Video Codec SDK Version: 9.1.23
 - Python Version: 3.8

**Screenshots**

![Screenshot from 2022-03-29 12-10-45](https://user-images.githubusercontent.com/53269135/160537905-2108568e-caeb-4863-a6d6-420a9463fe8c.png)

**Comment by rarzumanyan** [comment] 2022-03-29 06:24
Hi @pdd-999 

Have you tried https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecodeRTSP.py?

**Comment by pdd-99** [comment] 2022-03-29 07:14
@rarzumanyan I have tried `SampleDecodeRTSP.py` and it worked perfectly. But what's wrong with my provided script? I don't want to use the `subprocess.Popen` cause I want to have full control in the "Python layer".

**Comment by pdd-999** [comment] 2022-03-29 07:33
@rarzumanyan I have tried `SampleDecodeRTSP.py` and it worked perfectly. But what's wrong with my provided script? I don't want to use the `subprocess.Popen` cause I want to have full control in the "Python layer".

**Comment by rarzumanyan** [comment] 2022-03-29 07:48
Hi @pdd-999 

>But what's wrong with my provided script?

There's nothing wrong with your script.
Built-in VPF demuxer relies on FFMpeg C API underneath but it's not as good as that of ffmpeg application. Built-in demuxer works fine with local files but it often struggles to cope with RTSP connection(s).

> I want to have full control in the "Python layer".

I have the same opinion. 
Couple years ago I've used the experimental branch of PyAV project which supports bitstream filters to do the demuxing in Python but unfortunately it was never merged into main branch.

**Comment by pdd-99** [comment] 2022-03-29 08:06
@rarzumanyan The problem is resolved to a certain extent. Thanks for your prompt reply.

**Comment by pdd-999** [comment] 2022-03-29 08:10
@rarzumanyan The problem is resolved to a certain extent. Thanks for your prompt reply.

**Comment by rarzumanyan** [comment] 2022-03-29 08:13
Thanks for the update, @pdd-999 

Closing this issue as resolved. Please feel free to reopen in case it's not.

**Closed by rarzumanyan** 2022-03-29 08:13 UTC
