### ISSUE TITLE
seek discussion

### ISSUE THREAD

**Issue by lferraz** [NVIDIA/VideoProcessingFramework#178] opened 2021-03-24 13:08 UTC
Thank you so much @rarzumanyan for your work!!!

I opened this issue because it is easy to discuss and track this feature here.

I checked the last version of `seek` and there are some weird things. Anyway the problem with the instability is solved. :)

Now, I detected some weird things:
**1.** Some fields in `PacketData` are empty when getting the data directly from `DecodeSingleSurface()`.
    E.g. the next line
    `nvDec2.DecodeSingleSurface(nvc.SeekContext(1000), packet_data=b)`
   provides in `b` the next values:
    ```
    dts:0
    duration:6000
    pos:0
    pts:6000000
    ```
    So, `dts` and `pos` are invalid. Using `LastPacketData()` the returned values are correct, so there is an issue in the `DecodeSingleSurface()` method.

**2.** `duration` in `PacketData`  is incorrect when getting the data directly from `DecodeSingleSurface()`
  I checked the `pts`, `dts`, `duration` and `position` using `ffprobe` and the numbers are not the same.
  However, using `LastPacketData()` the returned values are the same as in `ffprobe`.
  E.g.
  ```
  p1 = nvc.PacketData()
  p2 = nvc.PacketData()
  nvDec.DecodeSingleSurface(nvc.SeekContext(1), packet_data=p1)
  nvDec.LastPacketData(p2)
  ```
  in this case `p1 != p2` being `p2` == to the numbers provided by `ffprobe`

**3.** One version of `DecodingSingleSurface()` is missing, concretely the one accepting only the `PacketData` structure. Since the C++ method exists I assume we only need to add:
```
.def("DecodeSingleSurface",
           py::overload_cast<PacketData &>(
               &PyNvDecoder::DecodeSingleSurface),
          py::arg("packet_data"),
          py::return_value_policy::take_ownership)
```

**4.** And when I try to go to frame 1, goes to frame 3 :S.

E.g.
```
nvDec.DecodeSingleSurface()
nvDec.LastPacketData(p)
// pts here is 5400
nvDec.DecodeSingleSurface()
nvDec.LastPacketData(p)
// pts here is 10800
nvDec.DecodeSingleSurface()
nvDec.LastPacketData(p)
// pts here is 18000
```

In the same video if I use `nvc.SeekContext(1)`:
```
nvDec.DecodeSingleSurface(nvc.Seek_Context(1))
nvDec.LastPacketData(p)
// pts here is 18000
```
So it is the same `pts` as in the 3rd call in the prev example.

**5.** I cannot go to frame 0.
this line `nvDec.DecodeSingleSurface(nvc.Seek_Context(0))` moves to the next frame not to the frame 0.

**6.** I can put negative numbers in `nvc.SeekContext(-1)` (in this case the seek is not doing anything, it is jumping to the next frame)

**Comment by lferraz** [comment] 2021-03-24 14:51
I did another experiment:

```
nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
nvDec2 = nvc.PyNvDecoder(encFilePath, gpuID)

frame_id = 100
while frame_id:
  rawSurface = nvDec.DecodeSingleSurface()
  frame_id -= 1

rawSurface2 = nvDec2.DecodeSingleSurface(nvc.SeekContext(frame_id))

// in theory both rawSurface should be the same but the packet data from both is very different
p1 = nvc.PacketData()
p2 = nvc.PacketData()
nvDec.LastPacketData(p1)
nvDec2.LastPacketData(p2)
```

`p1` contains:
```
dts:598500
duration:6300
pos:6304913
pts:598500
```

`p2` contains:
```
dts:468000
duration:4500
pos:5197601
pts:468000
```

the diff in frames between both is 22. They are not keyframes, the GOP is 15.

**Comment by rarzumanyan** [comment] 2021-03-24 14:54
@lferraz 
`frame_id=-1` is used as magic constant in default `SeekContext` constructor.
This is probably not the greatest idea and it needs to be fixed but what behavior do you expect from demuxer when you search for frame of number -1?

**Comment by lferraz** [comment] 2021-03-24 15:00
> @lferraz
> `frame_id=-1` is used as magic constant in default `SeekContext` constructor.
> This is probably not the greatest idea and it needs to be fixed but what behavior do you expect from demuxer when you search for frame of number -1?

I was expecting an exception. In fact I've not checked what happen if I ask for an invalid frame number bigger than the total number of frames

**Comment by rarzumanyan** [comment] 2021-03-24 15:03
>I was expecting an exception.

Fair enough, I'll modify the behavior of default constructor.

>In fact I've not checked what happen if I ask for an invalid frame number bigger than the total number of frames

That also can be checked, AVFormatContext keeps number of frames in video stream.

**Comment by lferraz** [comment] 2021-03-24 15:07
> > I was expecting an exception.
> 
> Fair enough, I'll modify the behavior of default constructor.
> 
> > In fact I've not checked what happen if I ask for an invalid frame number bigger than the total number of frames
> 
> That also can be checked, AVFormatContext keeps number of frames in video stream.

Another option, for these case ir returning `false`

**Comment by rarzumanyan** [comment] 2021-03-24 15:17
Pushed the commit to `seek_support_new`, please check it out.
Now constructor throws if called with negative `seek_frame`.
Decode function throws if seeking for frame number outside the range.
Number of frames in stream can be queried from Demuxer with `GetParams`

**Comment by lferraz** [comment] 2021-03-24 16:41
> Now constructor throws if called with negative `seek_frame`.

It works fine!!!

> Decode function throws if seeking for frame number outside the range.

It is not working properly to me...
```
nvDec = nvc.PyNvDecoder(encFilePath, gpuID)
nvDec.DecodeSingleSurface(nvc.SeekContext(1))
```
Raises the exception:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Seek frame exceeds number of frames in stream
```

> Number of frames in stream can be queried from Demuxer with `GetParams`

I think giving access to this info could also be interesting. I can create a branch for this with this minor improvement. Are you agree?

**Comment by lferraz** [comment] 2021-03-24 17:36
I checked the value of `Numframes()` abd it is incorrect. It says 1. So, this is the reason for the error in my previous comment.
Moreover, I also checked the framerate and it is incorrect, in my video it is 15 and the method returns 100.

```
nvDec.Numframes()
1
nvDec.Framerate()
100.0
```

**Comment by rarzumanyan** [comment] 2021-03-24 17:57
@lferraz 

>I checked the value of Numframes() abd it is incorrect. It says 1

The issue with incorrect number of frames was fixed by getting it from stream instead of codecpar.
Shows correct number of frames on my local video.

>Moreover, I also checked the framerate and it is incorrect, in my video it is 15 and the method returns 100.

That's strange, can't reproduce on local machine. It shows me correct FPS value for test video I'm using??

**Comment by lferraz** [comment] 2021-03-24 18:03
> What does `ffprobe` say about the FPS?

Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 8170 kb/s, 15 fps, 100 tbr, 90k tbn, 15 tbc (default)

**Comment by lferraz** [comment] 2021-03-24 18:08
> @lferraz
> 
> > I checked the value of Numframes() abd it is incorrect. It says 1
> 
> The issue with incorrect number of frames was fixed by getting it from stream instead of codecpar.
> Shows correct number of frames on my local video.

Now i got: 
```
nvDec3.Numframes()
3391
nvDec3.Framerate()
100.0 
```

the number of frames is correct.

**Comment by rarzumanyan** [comment] 2021-03-24 18:12
Great!

Any chance you can upload your hevc video? I'd like to see into with bitstream analyzer.
FPS is calculated so simple, it's just
https://github.com/NVIDIA/VideoProcessingFramework/blob/67c2ef385ff33a09b9cb2ece2edd32535a32b132/PyNvCodec/TC/src/FFmpegDemuxer.cpp#L367-L368

Doesn't look like there's too much room for error.

**Comment by lferraz** [comment] 2021-03-24 18:21
I will send you the link by email :)

**Comment by rarzumanyan** [comment] 2021-03-25 12:33
@lferraz 

Thanks for sharing the video.
Delving into ffmpeg guts doesn't clarify a thing:

First one says it's 100 FPS video:
```cpp
/**
 * Real base framerate of the stream.
 * This is the lowest framerate with which all timestamps can be
 * represented accurately (it is the least common multiple of all
 * framerates in the stream). Note, this value is just a guess!
 * For example, if the time base is 1/90000 and all frames have either
 * approximately 3600 or 1800 timer ticks, then r_frame_rate will be 50/1.
 */
fmtc->streams[videoStream]->r_frame_rate.num = 100;
fmtc->streams[videoStream]->r_frame_rate.den= 1;
```

Second one clearly indicates it's 15 FPS video:
```cpp
/**
 * This is the fundamental unit of time (in seconds) in terms
 * of which frame timestamps are represented. For fixed-fps content,
 * timebase should be 1/framerate and timestamp increments should be
 * identically 1.
 * This often, but not always is the inverse of the frame rate or field rate
 * for video. 1/time_base is not the average frame rate if the frame rate is not
 * constant.
 *
 * Like containers, elementary streams also can store timestamps, 1/time_base
 * is the unit in which these timestamps are specified.
 * As example of such codec time base see ISO/IEC 14496-2:2001(E)
 * vop_time_increment_resolution and fixed_vop_rate
 * (fixed_vop_rate == 0 implies that it is different from the framerate)
 *
 * - encoding: MUST be set by user.
 * - decoding: the use of this field for decoding is deprecated.
 *             Use framerate instead.
 */
fmtc->streams[videoStream]->codec->time_base.num = 1;
fmtc->streams[videoStream]->codec->time_base.den = 15;
```

Need more time to go through this.

**Comment by lferraz** [comment] 2021-03-25 15:24
I tried with another video, recorded with the same camera, and it is providing the correct fps.

```
nvDec.Numframes()
21219
nvDec.Framerate()
15.0
```

I've checked `ffprobe` in this second video and:
`Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 6142 kb/s, 15 fps, 15 tbr, 90k tbn, 15 tbc (default)`
and
`r_frame_rate=15/1`

Comparing the oputput of `ffprobe` I've seen one curious thing. In the first one I got `100 tbr` and in the second one `15 tbr`. I've no idea about the meaning of tbr but maybe it is related... or not XD

The output for the one you are testing:
`Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 8170 kb/s, 15 fps, 100 tbr, 90k tbn, 15 tbc (default)`
`r_frame_rate=100/1`

**Comment by rarzumanyan** [comment] 2021-03-25 16:22
@lferraz 

>they are not constant because we record videos from the IP cameras using the ffmpeg command to record from rtsp sources.

In such case the `Seek` may also behave in weird fashion because it converts frame number to timestamp.

**Comment by lferraz** [comment] 2021-03-29 15:07
I checked with `pyav` and also returns 100 fps.

**Comment by rarzumanyan** [comment] 2021-03-29 17:01
Hi @lferraz 

Packets demuxed with PyAV require some special attention and you also need specific PyAV branch which supports bitstream filters (such as mpeg to annexb filter which is used to extract Annex.B Access Units from containers).

There’s a long thread in issue name “ability to work alongside PyAV”, please take a look at that if you like.

Long story short, we were able to implement seamless integration between PyAV and VPF but experimental PyAV branch which supports bitstream filters isn’t merged with master yet. We have pinged PyAV maintainers without any success.

P. S.
I’m OOO this week, will continue to work on your PR as soon as I’m back.

**Closed** 2021-05-04 09:32 UTC
