### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dbermond** [NVIDIA/VideoProcessingFramework#266] opened 2021-10-29 19:38 UTC
**Describe the bug**
Both the git master branch and the tagged 1.1 release fails to build for me, giving lots of errors of the following type:

```
/build/nvidia-vpf-git/src/VideoProcessingFramework/PyNvCodec/src/PyNvDecoder.cpp: In lambda function:
/build/nvidia-vpf-git/src/VideoProcessingFramework/PyNvCodec/src/PyNvDecoder.cpp:658:48: error: designated initializers cannot be used with a non-aggregate type ‘DecodeContext’
  658 |                                  .flush = false};
      |                                                ^
```

Complete build error log [here](https://paste.ee/p/BGW1V).

**To Reproduce**
```
$ git clone https://github.com/NVIDIA/VideoProcessingFramework.git
$ export CUDAToolkit_ROOT='/opt/cuda'
$ export CXXFLAGS+=' -I/opt/cuda/include'
$ export  LDFLAGS+=' -L/opt/cuda/lib64'
$ cmake -B build -S VideoProcessingFramework \
        -DCMAKE_BUILD_TYPE:STRING='None' \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DCMAKE_CUDA_COMPILER:FILEPATH='/opt/cuda/bin/nvcc' \
        -DCMAKE_SKIP_RPATH:BOOL='YES' \
        -DGENERATE_PYTHON_BINDINGS:BOOL='TRUE' \
        -DVIDEO_CODEC_SDK_INCLUDE_DIR:PATH='/usr/include/nvidia-sdk' \
        -Wno-dev
$ make -C build
```

**Expected behavior**
The build process to complete without errors.

**Screenshots**
Not applicable. Terminal only.

**Desktop:**
 - OS: Arch Linux x86_64
 - Nvidia driver version: 495.44
 - CUDA Version: 11.4.2
 - Video Codec SDK Version: 11.1.5
 - Python Version: 3.9.7

**Additional context**
 - Compiler: gcc 11.1.0
 - CMake: 3.21.4
 - Version 1.0 builds fine for me

**Comment by rarzumanyan** [comment] 2021-10-29 19:43
Hi @dbermond 

This must be compiler-specific error.
Allow me some time for fix, it's relatively simple to issue, just need to replace assignment with constructor call.
Meanwhile I recommend you to use 1.0 release.

**Comment by rarzumanyan** [comment] 2021-10-29 20:50
@dbermond 

Please check out `issue_266` branch, I've pushed the patch which replaces assignment with ctor call.
If it fixes the issue on your side - let me know, I'll merge to `master`.

**Comment by dbermond** [comment] 2021-10-29 21:08
Branch `issue_266` builds fine for me only when I apply the patch from commit abba228ab1fe7c446efd52ed9949410ae2224fde to it.

Really simple fix :)

Thank you for working on this issue.

**Comment by rarzumanyan** [comment] 2021-10-29 21:13
@dbermond 

`master` already has your PR merged, so as soon as `issue_266` is merged to `master`, it will not have a missing header problem.

**Comment by rarzumanyan** [comment] 2021-10-29 21:15
Merged to `master`, please check ToT.
In case the problem isn't resolved, please reopen the issue.

**Closed by rarzumanyan** 2021-10-29 21:15 UTC

**Comment by dbermond** [comment] 2021-10-29 21:19
I can confirm that the git master branch is now building fine for me.

Thank you for fixing this.

**Comment by rarzumanyan** [comment] 2021-10-29 21:22
You’re welcome!
Thanks for bringing this up.
