### ISSUE TITLE
SampleDecode RTSP code freezes at -> success = nvDec.DecodeSingleFrame(rawFrameNV12)

### ISSUE THREAD

**Issue by u93** [NVIDIA/VideoProcessingFramework#132] opened 2020-11-12 02:05 UTC
**Describe the bug**
When running the Python sample for SampleDecode.py using:

 `python3.6 SampleDecode.py 0 rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov test.nv12`, 

which is a healthy RTSP stream, verified by running command:

`ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov -c:a copy -c:v h264_nvenc -b:v 5M output.mp4`

Code freezes when it reaches the line `success = nvDec.DecodeSingleFrame(rawFrameNV12)` and does not move forward in the `while True` loop...

**Expected behavior**
Proper RTSP stream frames decoding, similar to what FFmpeg would do, since VPF uses FFmpeg...

**Desktop (please complete the following information):**
 - OS: 
**Host** -> Ubuntu 18.4
**VPF running in Docker Container** -> nvcr.io/nvidia/tensorrt:20.10-py3 which also uses Ubuntu
 - Nvidia driver version -> **455**
 - CUDA Version -> **11.1**
 - Video Codec SDK -> **9.1.23**
 - Python Version -> **3.6.9**

**Additional context**
FFmpeg installation steps in Dockerfile

```
RUN mkdir /usr/local/ffmpeg
RUN git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git && cd nv-codec-headers && sudo make install && cd ..
RUN git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg/
RUN apt-get install -y build-essential yasm cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev
COPY configure ffmpeg/
RUN cd ffmpeg && \
    ./configure --enable-nonfree --enable-cuda-sdk --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --prefix=/usr/local/ffmpeg --enable-shared --disable-doc && \
    make -j8 && \
    make install
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/ffmpeg/lib/
ENV PATH $PATH:/usr/local/ffmpeg/bin
```

VIDEO CODEC SDK setup
```
ADD Video_Codec_SDK_9.1.23.zip /
RUN apt-get update &&  apt-get install -y --no-install-recommends unzip cmake git && \
    unzip -q /Video_Codec_SDK_9.1.23.zip -d /usr/local/lib/ && \
    rm /Video_Codec_SDK_9.1.23.zip && \
    mkdir /usr/local/vpf && \
    cd / && \
        git clone https://github.com/NVIDIA/VideoProcessingFramework.git && \
        cd VideoProcessingFramework && \
        mkdir build && \
        cd build && \
        cmake \ 
            -DFFMPEG_DIR:PATH="/usr/local/ffmpeg" \
            -DVIDEO_CODEC_SDK_DIR:PATH="/usr/local/lib/Video_Codec_SDK_9.1.23" \
            -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
            -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/vpf" \
            # -DAVCODEC_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            # -DAVFORMAT_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            # -DAVUTIL_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            # -DSWRESAMPLE_LIBRARY="/usr/local/ffmpeg/lib/libswresample.so" \
            # -DAVFORMAT_LIBRARY="/usr/local/ffmpeg/lib/libavformat.so" \
            # -DAVCODEC_LIBRARY="/usr/local/ffmpeg/lib/libavcodec.so" \
            # -DAVUTIL_LIBRARY="/usr/local/ffmpeg/lib/libavutil.so" \
            -DPYTHON_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython3.6m.so" \
            -DPYTHON_EXECUTABLE="/usr/bin/python3.6" .. && \
        make -j$(nproc) && \
        make install

ENV PYTHONPATH $PYTHONPATH:/usr/local/vpf/bin
```

**UPDATE:**
Here are the installation logs for VPF, not sure if those warnings are supposed to show up:
```
+ cmake -DFFMPEG_DIR:PATH=/usr/local/ffmpeg -DVIDEO_CODEC_SDK_DIR:PATH=/usr/local/lib/Video_Codec_SDK_9.1.23 -DGENERATE_PYTHON_BINDINGS:BOOL=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/vpf -DVIDEO_CODEC_SDK_INCLUDE_DIR=/usr/local/lib/Video_Codec_SDK_9.1.23/include -DAVCODEC_INCLUDE_DIR:PATH=/usr/local/ffmpeg/include -DAVFORMAT_INCLUDE_DIR:PATH=/usr/local/ffmpeg/include -DAVUTIL_INCLUDE_DIR:PATH=/usr/local/ffmpeg/include -DSWRESAMPLE_LIBRARY=/usr/local/ffmpeg/lib/libswresample.so -DAVFORMAT_LIBRARY=/usr/local/ffmpeg/lib/libavformat.so -DAVCODEC_LIBRARY=/usr/local/ffmpeg/lib/libavcodec.so -DAVUTIL_LIBRARY=/usr/local/ffmpeg/lib/libavutil.so -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_EXECUTABLE=/usr/bin/python3.6 ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.1.74
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Searching for FFmpeg libs in /usr/local/ffmpeg/lib
-- Searching for FFmpeg headers in /usr/local/ffmpeg/include
-- Searching for Video Codec SDK headers in /usr/local/lib/Video_Codec_SDK_9.1.23/include folder
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.5") 
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- pybind11 v2.3.dev0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /VideoProcessingFramework/build
++ nproc
+ make -j8
Scanning dependencies of target TC_CORE
[ 12%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Token.cpp.o
[ 12%] Building CXX object PyNvCodec/TC/TC_CORE/CMakeFiles/TC_CORE.dir/src/Task.cpp.o
[ 18%] Linking CXX shared library libTC_CORE.so
[ 18%] Built target TC_CORE
Scanning dependencies of target TC
[ 31%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/MemoryInterfaces.cpp.o
[ 31%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvEncoder.cpp.o
[ 37%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvDecoder.cpp.o
[ 50%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvEncoderCuda.cpp.o
[ 50%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/FFmpegDemuxer.cpp.o
[ 56%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o
[ 62%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NppCommon.cpp.o
[ 68%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/TasksColorCvt.cpp.o
[ 75%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/NvCodecCliOptions.cpp.o
[ 81%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/FfmpegSwDecoder.cpp.o
/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp: In member function 'AVFormatContext* FFmpegDemuxer::CreateFormatContext(const char*, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)':
/VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:292:19: warning: 'void av_register_all()' is deprecated [-Wdeprecated-declarations]
   av_register_all();
                   ^
In file included from /VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:24:0,
                 from /VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp:14:
/usr/local/ffmpeg/include/libavformat/avformat.h:1944:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
/VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp: In constructor 'VPF::FfmpegDecodeFrame_Impl::FfmpegDecodeFrame_Impl(const char*, AVDictionary*)':
/VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:69:21: warning: 'void av_register_all()' is deprecated [-Wdeprecated-declarations]
     av_register_all();
                     ^
In file included from /VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:22:0:
/usr/local/ffmpeg/include/libavformat/avformat.h:1944:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
/VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:103:49: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
     avctx = fmt_ctx->streams[video_stream_idx]->codec;
                                                 ^~~~~
In file included from /VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:22:0:
/usr/local/ffmpeg/include/libavformat/avformat.h:884:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:103:49: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
     avctx = fmt_ctx->streams[video_stream_idx]->codec;
                                                 ^~~~~
In file included from /VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:22:0:
/usr/local/ffmpeg/include/libavformat/avformat.h:884:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
/VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:103:49: warning: 'AVStream::codec' is deprecated [-Wdeprecated-declarations]
     avctx = fmt_ctx->streams[video_stream_idx]->codec;
                                                 ^~~~~
In file included from /VideoProcessingFramework/PyNvCodec/TC/src/FfmpegSwDecoder.cpp:22:0:
/usr/local/ffmpeg/include/libavformat/avformat.h:884:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
[ 87%] Linking CXX shared library libTC.so
[ 87%] Built target TC
Scanning dependencies of target PyNvCodec
[ 93%] Building CXX object PyNvCodec/CMakeFiles/PyNvCodec.dir/src/PyNvCodec.cpp.o
[100%] Linking CXX shared library PyNvCodec.cpython-36m-x86_64-linux-gnu.so
[100%] Built target PyNvCodec
+ make install
[ 18%] Built target TC_CORE
[ 87%] Built target TC
[100%] Built target PyNvCodec
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/vpf/bin/libTC_CORE.so
-- Installing: /usr/local/vpf/bin/libTC.so
-- Installing: /usr/local/vpf/bin/PyNvCodec.cpython-36m-x86_64-linux-gnu.so
-- Installing: /usr/local/vpf/bin/SampleDecode.py
-- Installing: /usr/local/vpf/bin/SampleEncode.py
-- Installing: /usr/local/vpf/bin/SampleDecodeSw.py
-- Installing: /usr/local/vpf/bin/SampleDecodeMultiThread.py
-- Installing: /usr/local/vpf/bin/SampleEncodeMultiThread.py
```

**Comment by u93** [comment] 2020-11-12 16:58
Same situation happens with Video Codec SDK `10.0.26`, so I wonder if it's something related to FFmpeg and if there is some way to actually see the where is it failing, like a `verbose` mode.

The RTSP communication starts successfully, so maybe there is some parameter that can be passed as a dict here `nvDec = nvc.PyNvDecoder(encFilePath, gpuID)` that could help this...

**Comment by philipp-schmidt** [comment] 2020-11-23 18:21
Hi,

I can play back your exemplary stream just fine with a similar docker build setup. However, I testes a multitude of RTSP capable cameras and very many of them get stuck at the very same part of the code like you describe it...

Can you try to install ffmpeg via apt instead of compiling it? That's the only real difference that I can see right now between our setups.

**Comment by philipp-schmidt** [comment] 2020-11-23 18:30
@rarzumanyan any chance you can give us a hint where to start to search for the cause of something like this? I have tested 9 different RTSP cameras, and 5 of them work just fine, but the rest is stuck at the very same part @u93 describes.
Here are my ffprobe results whether the camera can be read just fine or gets stuck at `rawSurface = self.nvDec.DecodeSingleSurface()`

```
Video: h264 (Main), yuvj420p(pc, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
---- OK

Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
---- OK

Video: h264 (Main), yuvj420p(pc, progressive), 1280x720, 29.83 tbr, 90k tbn, 180k tbc
---- OK

Video: h264 (Baseline), yuv420p(tv, smpte170m/bt470bg/smpte170m, progressive), 1920x1080, 90k tbr, 90k tbn, 180k tbc
---- OK

Video: h264 (High), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
---- FAIL

Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn, 180k tbc
---- FAIL

Video: h264 (Baseline), yuvj420p(pc, bt709, progressive), 2992x2992 [SAR 1:1 DAR 1:1], 30 tbr, 90k tbn, 180k tbc
---- OK

h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 30 fps, 30 tbr, 90k tbn, 180k tbc
---- FAIL

Video: h264 (High), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 1:1 DAR 168:95], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
---- FAIL
```

**Comment by philipp-schmidt** [comment] 2020-11-23 18:46
okay, I just found this issue: #77 and all my failing cameras are actually Axis cameras...
I will open up the discussion in the other thread.

**Comment by rarzumanyan** [comment] 2020-11-23 18:46
Hi @philipp-schmidt 

>any chance you can give us a hint where to start to search for the cause of something like this?

Unfortunately I can't give you any advice on this topic as I'm running out of depth.
RTSP video problems are >90% of user issues with VPF and every time it's something being wrong with one IP camera and everything being fine with another. 

@maxclaey is currently experimenting with PyAV (Python wrapper for FFmpeg) interoperability, as soon as I have some time I'll also start working on this. VPF already supports stand-alone demuxing, so I hope to replace built-in demuxer (which is based on FFmpeg C API) with external PyAV demuxer. Working with network input is really outside the scope of this project and it's the main source of user complains now. 

I understand the disappointment people experience with RTSP cameras support and I hope that PyAV interoperability will solve this issue.

**Comment by philipp-schmidt** [comment] 2020-11-23 20:44
@rarzumanyan actually there is absolutely nothing to be dissappointed with in this repo, on the contrary. I very much appreciate the time you (and nvidia) put into maintaining this code and offering it as open source. I was experimenting with [piping nv-codec ffmpeg output](https://medium.com/@fanzongshaoxing/use-ffmpeg-to-decode-h-264-stream-with-nvidia-gpu-acceleration-16b660fd925d) into python code from stdin and also tried [gstreamer plugins](https://medium.com/@fanzongshaoxing/use-nvidia-deepstream-to-accelerate-h-264-video-stream-decoding-8f0fec764778) in a similar fashion (which is of course what deepstream uses under the hood), but both ways felt very hacky and were unstable.

I have not yet exhausted all of my investigative energy on the issue ;) But I might be using a CPU fallback option for those specific cases for now. Would be glad to contribute on the PyAV front as best I can after my current project, I will follow the progress if you two will be sharing it.

**Comment by u93** [comment] 2020-12-05 20:31
Hi @philipp-schmidt sorry I took such a long time to respond... Insanely busy... Now that I think about it, I have also been testing with Axis cameras so maybe that's why it's freezing for me. I never tested with another cameras, but will definitely try it. 

On the other side, the nice stuff about the FFmpeg build that I use is the possibility of using HW decoding, I'll try it with the `apt` one as soon as I have a chance. You can also see how the FFmpeg binary on `apt` was build, and it has a ton of flags, so maybe trying to build it with the flags that the binary in `apt` has  with CUDA flags and see if it works would be nice...

I need to spend some time on this for sure, I'll post here if I can get an improvement... On the Axis cameras issue, @rarzumanyan is it possible to have some kind of debug mode where we could see with a bit more detail what's going in VPF? It's hard to actually try to debug if nothing is printed to console...

Thanks!

**Comment by u93** [comment] 2020-12-05 20:37
It would also be nice if we could define `safe` RTSP stream settings for VPF, in example, FFmpeg reencoding using HW decoding it's super low on resource usage. I agree with @philipp-schmidt about how hacky it feels to pipe FFmpeg into Python code, plus is not that efficient or stable enough for production systems, still have to do color conversion in case that you will be using OpenCV for operations on the frames and other stuff that are CPU intensive... 

Video ingestion is a tricky issue and there are not many stable or efficient solutions published that can actually handle a high number of video streams in a stable and efficient way. I'll be publishing any improvement here, and I'll be glad to contribute and test this project...

Thanks!

**Comment by philipp-schmidt** [comment] 2020-12-06 01:01
What's the point of using ffmpeg with cuda hw acceleration if you are using VPF for decoding?

**Comment by u93** [comment] 2020-12-06 02:13
In example, one of the use cases of my application it's the re-encode and re-stream of RTSP/RTMP Streams, which when done using the `apt` FFmpeg it's insanely CPU intensive, and as far as I know, VPF is not designed for that...

**Comment by rarzumanyan** [comment] 2022-04-19 07:27
Closing this issue because new `SampleDecodeRTSP.py` is available which uses ffmpeg subprocess for demuxing.

**Closed by rarzumanyan** 2022-04-19 07:27 UTC
