### ISSUE TITLE
SampleColorConversion fail

### ISSUE THREAD

**Issue by tetelias** [NVIDIA/VideoProcessingFramework#14] opened 2020-02-26 22:05 UTC
I built the library with python 3.7, CUDA 10.0, Video Codec SDK v9.0 and ffmpeg 4.2.2.
All of the tests run well, except SampleColorConversion.py which fails immediately with 
![Screenshot from 2020-02-27 01-10-02](https://user-images.githubusercontent.com/29153358/75392848-ecbcfc80-58fd-11ea-9c07-a933ca639007.png)

While example from https://devblogs.nvidia.com/vpf-hardware-accelerated-video-processing-framework-in-python/ fails with 
![Screenshot from 2020-02-27 01-08-13](https://user-images.githubusercontent.com/29153358/75392770-c5662f80-58fd-11ea-8be1-205da763e994.png)

**Comment by rarzumanyan** [comment] 2020-02-27 08:19
Hi,

Can you add following line to the SampleColorConversion to see if encoder returns correct frame size:
```python
width, height = nvEnc.Width(), nvEnc.Height()
nvUpl = nvc.PyFrameUploader(nvEnc.Width(), nvEnc.Height(), nvc.PixelFormat.YUV420, gpuID)
```

If it does, I'll add more verbose exception throwing code to see what's exactly going wrong within PyFrameUploader constructor.

**Comment by tetelias** [comment] 2020-02-27 08:57
Same traceback except it's now on line 54, so it seems frame size is not a problem.

**Comment by rarzumanyan** [comment] 2020-02-27 09:18
I mean, did you check that frame width and height have sane values?

**Comment by tetelias** [comment] 2020-02-27 10:15
Yes, 1920 1080 printed for Bunny.

**Comment by tetelias** [comment] 2020-02-28 11:02
Any ideas where to look further?

**Comment by rarzumanyan** [comment] 2020-02-28 11:37
Can you launch the sample in parallel with `nvidia-smi dmon` in separate console window? 
It will show the amount of GPU memory used throughout the process.
BTW do you run into issues with color conversion sample only, or something else fails too?

**Comment by tetelias** [comment] 2020-02-28 14:51
Just re-run all the Sample files and results are:
I downloaded "big_buck_bunny_1080p_h264.mov" from blender(size=725,106,140)
SampleTranscode.py generates "big_buck_bunny_1080p.h264" (size=195,441,743) (307MB GPU memory)
SampleTranscodeOneToN.py creates the same file/same size plus "big_buck_bunny_720p.hevc" (size=101,799,590) (324MB GPU memory)
SampleSufraceDownload.py generates "big_buck_bunny_1080p_h264.nv12" (size=44,525,376,000) (259MB GPU memory)
SampleEncode.py produces "big_buck_bunny_1080p.h264" (size=195,441,743) from .nv12 file just generated (193MB GPU memory)
SampleFrameUpload.py creates "big_buck_bunny_1080p_h264.h264" (size=195,441,743) from the same .nv12 file (193MB GPU memory)
GPU utilization is 3-8% for 1080ti
So it seems these 5 files are working fine or at least the same way.

SampleDecode.py creates "big_buck_bunny_1080p_h264.nv12"  file as well but it continues to run until disk space is exhausted.  (255MB GPU memory)

SampleColorConversion.py fails immediately the same way it was described in the first post.

**Comment by rarzumanyan** [comment] 2020-02-28 14:57
Does SampleColorConversion generate raw yuv420 file?

**Comment by tetelias** [comment] 2020-02-28 14:58
Yes, it's created with size of 0

**Comment by rarzumanyan** [comment] 2020-02-28 16:08
Ok so it means vpf struggles to decode and / or convert nv12 -> yuv420 at first place.
We need to find out the reason before going to second part, in which yuv420 file is being encoded.
My advice is to step through the code with python debugger or simply put print to get verbose error messages like below:

```python
# We don't need to decode whole file
threshold = 30
frame = 0

while True:
    rawSurfaceNV12 = nvDec.DecodeSingleSurface()
    if (rawSurfaceNV12.Empty()):
        print('Failed to decode video frame')
        break

    rawSurfaceYUV420 = nvCvt.Execute(rawSurfaceNV12)
    if (rawSurfaceYUV420.Empty()):
        print('Failed to convert NV12 to YUV420')
        break

    rawFrameYUV420 = nvDwl.DownloadSingleSurface(rawSurfaceYUV420)
    if not (rawFrameYUV420.size):
        print('Failed to copy YUV420 frame from GPU')
        break

    frameByteArray = bytearray(rawFrameYUV420)
    decFile.write(frameByteArray)

    frame += 1
    if (frame > threshold):
        break
```

**Comment by tetelias** [comment] 2020-02-28 19:28
Result is "Failed to copy YUV420 frame from GPU".

Changing from YUV420 to RGB yields same result - failing on SurfaceDownloader

Also running
```
nvDec = nvc.PyNvDecoder(encFile, gpuID)
rawFrame = nvDec.DecodeSingleFrame()
```
makes rawFrame a uint8 numpy array of size (3110400,).

**Comment by ygao12** [comment] 2020-04-13 07:21
I also met problem when testing with `SampleColorConversion.py` .
I notice that  the first frame can be transformed and downloaded(but all pixels seem to be zero), when second frame is transformed by `nvCvt.Execute(rawSurfaceNV12)`, it can not download from gpu device caused by `if (CUDA_SUCCESS != cuMemcpy2DAsync(&m, stream))` check failure.
Another problem I noticed is that if I new a `PySurfaceConverter` class, CudaResMgr will cause crash when destructor is called. Crashed at this line`ThrowOnCudaError(cuStreamDestroy(cuStream), __LINE__);`. Core info is
`CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS
an illegal memory access was encountered`

**Comment by rarzumanyan** [comment] 2020-04-13 08:25
Hi @ygao12 

> `CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS an illegal memory access was encountered`

This means that NPP color conversion function has attempted to access illegal memory address. 
All further CUDA operations within same context will return this error code.
My advice here is to update CUDA toolkit to latest version (10.2).

Is this problem specific to the SampleColorConversion only?

**Comment by ygao12** [comment] 2020-04-13 13:01
> Hi @ygao12
> 
> > `CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS an illegal memory access was encountered`
> 
> This means that NPP color conversion function has attempted to access illegal memory address.
> All further CUDA operations within same context will return this error code.
> My advice here is to update CUDA toolkit to latest version (10.2).
> 
> Is this problem specific to the SampleColorConversion only?

Yes, I only met this problem when doing ColorConversion. I will try CUDA toolkit 10.2. Thank you!

**Comment by ygao12** [comment] 2020-04-14 04:30
> Hi @ygao12
> 
> > `CUDA error: CUDA_ERROR_ILLEGAL_ADDRESS an illegal memory access was encountered`
> 
> This means that NPP color conversion function has attempted to access illegal memory address.
> All further CUDA operations within same context will return this error code.
> My advice here is to update CUDA toolkit to latest version (10.2).
> 
> Is this problem specific to the SampleColorConversion only?

Hello, I upgraded my CUDA toolkit to 10.2, but the same problem occurred. What should I try next?

**Comment by rarzumanyan** [comment] 2020-05-07 03:10
Hi @ygao12,

Please check out the latest version from master branch. It has multiple NPP issues fixed.

**Comment by ygao12** [comment] 2020-05-08 08:43
> Hi @ygao12,
> 
> Please check out the latest version from master branch. It has multiple NPP issues fixed.

Excellent! Thank you very much for fixing it. I pulled the latest version and it works very fine for me now. VPF is 3x faster than opencv on my GeForce RTX 2080 ti.

**Comment by rarzumanyan** [comment] 2020-05-08 09:02
Hi @ygao12 
Glad that it works fine for you!
Closing the issue.

**Closed by rarzumanyan** 2020-05-08 09:02 UTC
