### ISSUE TITLE
vpf decode get too much pitch and the out put video is colorless

### ISSUE THREAD

**Issue by stepstep123** [NVIDIA/VideoProcessingFramework#284] opened 2021-11-21 06:27 UTC

**Comment by stepstep123** [comment] 2021-11-21 11:39
AND img_tensors is a list saved tensors which are out of model,
when i use SamplePytorch, just decoder then encoder, the .nv12 is fine.
when i use SampleTensorRTResnet.py to decoder the video, then save them to list, next saved then, everything is ok. next decoder,the code as show above. the out put .nv12 have someproble, use ffmpeg  transfor to .mp4, the video is white -black and have some pitch.

the picture is one of the result video. i screenshoted it

**Comment by rarzumanyan** [comment] 2021-11-21 11:58
Hi @stepstep123 

It's difficult to tell what exactly happens in your program judging by short code sample.

Please find below a code snippet which I use to test ML inference on video frames.\
These functions are class methods but they shall be easy to follow themselves.

This is how you may decode any supported video frame to planar rgb tensor.
It's basically same to that in `SampleTorchResnet.py`:
```python
def decode_hw(self) -> nvc.Surface:
    """Decode single video frame with Nvdec, convert it to planar RGB.
    """
    # Decode with HW decoder
    nv12_surface = self.nvDec.DecodeSingleSurface()
    if not nv12_surface or nv12_surface.Empty():
        raise RuntimeError('Can not decode frame.')

    # Convert to packed RGB
    rgb_int = self.to_rgb.Execute(nv12_surface, self.cc_ctx)
    if not rgb_int or rgb_int.Empty():
        raise RuntimeError('Can not convert nv12 -> rgb.')

    # Convert to planar RGB
    rgb_pln = self.to_pln.Execute(rgb_int, self.cc_ctx)
    if not rgb_pln or rgb_pln.Empty():
        raise RuntimeError('Can not convert rgb -> rgb planar.')

    return rgb_pln

def decode_to_tensor(self) -> torch.Tensor:
    """Decode single video frame, convert it to torch.cuda.FloatTensor.
       Image will be planar RGB normalized to range [0.0; 1.0].
    """
    rgb_pln = self.decode_hw()

    if not rgb_pln or rgb_pln.Empty():
        raise RuntimeError('Can not convert rgb -> rgb planar.')

    surf_plane = rgb_pln.PlanePtr()
    img_tensor = pnvc.makefromDevicePtrUint8(surf_plane.GpuMem(),
                                             surf_plane.Width(),
                                             surf_plane.Height(),
                                             surf_plane.Pitch(),
                                             surf_plane.ElemSize())
    if img_tensor is None:
        raise RuntimeError('Can not export to tensor.')

    img_tensor.resize_(3, self.height(), self.width())
    img_tensor = img_tensor.type(dtype=torch.cuda.FloatTensor)
    img_tensor = torch.divide(img_tensor, 255.0)

    return img_tensor
```

And this is the function which accepts planar float cuda tensor from PyTorch and encodes it:
```python
def encode_from_tensor(self, tensor: torch.Tensor):
    """Encode single video frame from torch.cuda.FloatTensor.
       Tensor must have planar RGB format and be normalized to range [0.0; 1.0].
       Shape of the tensor must be (3, height, width).
    """
    if len(tensor.shape) != 3 and tensor.shape[0] != 3:
        raise RuntimeError(
            'Shape of the tensor must be (3, height, width)')

    tensor_w, tensor_h = tensor.shape[2], tensor.shape[1]
    if tensor_w != self.width():
        raise RuntimeError('Invalid input width.')

    if tensor_h != self.height():
        raise RuntimeError('Invalid input height.')

    img = torch.multiply(tensor, 255.0)
    img = img.type(dtype=torch.cuda.ByteTensor)

    rgb_planar = nvc.Surface.Make(
        nvc.PixelFormat.RGB_PLANAR, tensor_w, tensor_h, self.gpu_id)
    rgb_planar.PlanePtr().Import(img.data_ptr(), tensor_w, self.gpu_id)

    cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                                nvc.ColorRange.MPEG)
    yuv444 = self.to_yuv.Execute(rgb_planar, cc_ctx)
    if yuv444.Empty():
        raise RuntimeError('Can not convert to yuv444.')

    encFrame = np.ndarray(shape=(0), dtype=np.uint8)
    success = self.nvEnc.EncodeSingleSurface(yuv444, encFrame)
    if success:
        encByteArray = bytearray(encFrame)
        self.fout.write(encByteArray)
```

Encoder here is initialized to produce YUV444 video file, but you may convert to NV12 if you like.

**Comment by stepstep123** [comment] 2021-11-21 12:45
> 

thank your advice first.

the encode_from_tensor is almost the same as my code.

when i use your code to run, but error occur 
`surface_rgb.PlanePtr().Import(img_tensor.data_ptr(), w, gpuID)
RuntimeError: /opt/PyNvCodec/TC/src/MemoryInterfaces.cpp:452
CUDA error: CUDA_ERROR_INVALID_VALUE
invalid argument
`
when i use rgb_planar.PlanePtr().Import(img.data_ptr(), **tensor_w*3**, self.gpu_id)
everthing is ok. but the result is the same as above,  pitch and white-black video.

thank you so much, i really dont know the reason

**Comment by stepstep123** [comment] 2021-11-21 13:01
> Collaborator

some code may be in __init__ func. i guess they should be like this

`self.to_yuv  = nvc.PySurfaceConverter(tensor_w, tensor_h, **nvc.PixelFormat.RGB**, **nvc.PixelFormat.YUV444**, gpu_id)
rgb_planar.PlanePtr().Import(img.data_ptr(), **tensor_w**, self.gpu_id)`

**Comment by rarzumanyan** [comment] 2021-11-21 13:11
@stepstep123 

What pixel format does your NN expect? E. g. Resnet 50 wants planar rgb, but your network may want interleaved rgb as well.

**Comment by stepstep123** [comment] 2021-11-22 07:57
> 

thank your reply. here is new code "encode_from_tensor"
`

def encode2nv12(gpuID, img_tensors:list, encFilePath, dstFilePath):

    dstFile = open(dstFilePath, "wb")

    w, h = 720, 1280

    res = str(w) + 'x' + str(h)
    encFrame = np.ndarray(shape=(0), dtype=np.uint8)
    to_yuv444 = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.RGB_PLANAR, nvc.PixelFormat.YUV444, gpuID)
    nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': res}, gpuID)

    # Colorspace conversion contexts.
    # Here we use them just for illustration purposes.
    cc1 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_709,
                                          nvc.ColorRange.JPEG)
    cc2 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                          nvc.ColorRange.MPEG)
    for img_tensor in img_tensors:

        img_tensor = img_tensor[0] # [c, h, w] [3, 720, 1280]
        img_tensor = torch.multiply(img_tensor, 255.0)
        img_tensor = img_tensor.type(dtype=torch.cuda.ByteTensor)
        surface_rgb = nvc.Surface.Make(nvc.PixelFormat.RGB_PLANAR, w, h, gpuID)
        surface_rgb.PlanePtr().Import(img_tensor.data_ptr(), w, gpuID)
        cc2 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                            nvc.ColorRange.MPEG)
        
        surface_yuv = to_yuv444.Execute(surface_rgb, cc2)
        success = nvEnc.EncodeSingleSurface(surface_yuv, encFrame)
        if success:
            encByteArray = bytearray(encFrame)
            dstFile.write(encByteArray)
    '''
    while True:
        success = nvEnc.FlushSinglePacket(encFrame)
        if (success):
            encByteArray = bytearray(encFrame)
            dstFile.write(encByteArray)
        else:
            break
   '''

if __name__=="__main__":
     encode2nv12(0, img_tensors, None, "out.yuv")

`
when i get the result out.yuv. i use ffmpeg -f h264 -i out.yuv -vcodec copy out.mp4 
but the out.mp4 is not good 

![jiema](https://user-images.githubusercontent.com/43130195/142823918-038d9d0e-48c8-411b-96ac-d279f1470590.jpg)


the person should be colorful, but now only black-whith

**Comment by rarzumanyan** [comment] 2021-11-22 08:50
@stepstep123 

>`def encode2nv12(gpuID, img_tensors:list, encFilePath, dstFilePath)`

From the function name I assume that your encoder is configured to take NV12 input surfaces but you actually give it YUV444 surfaces to encode. 

These two formats have same Y plane layout, that's why your black and white component is fine. Also, YUV444 takes more place in memory then NV12 and because of that encoder doesn't cause memory access violation errors. However, U and V planes layout is different between NV12 and YUV444 which is the reason your video has broken colors.

There are 2 ways to address this:

1. Convert RGB > YUV420, then YUV420 > NV12, then give NV12 surface to encoder.
2. Configure your encoder to accept YUV444 frames when you create it:

```python
# These encoding parameters are for illustration purposes. 
# Use your actual parameters.
opts = {
  'preset': 'P4', 
  'tuning_info': 'high_quality', 
  'codec': 'h264', 
  's': '720x1280', 
  'bitrate': '10M'
}

# Note that you need to pass nvc.PixelFormat.YUV444 to encoder constructor.
# By default nvc.PixelFormat.NV12 is used.
self.nvEnc = nvc.PyNvEncoder(opts, gpu_id, nvc.PixelFormat.YUV444)
```

P. S.
Please note that YUV444 decoding support is not very common among consumer electronic devices. If you plan to use your code in production and deliver video after ML inference to customers, I recommend to stick to "usual" `PyNvEncoder` settings and follow path 1. 

If this program is for research / development or just your own internal use, videos encoded in YUV444 format are perfectly fine.

**Comment by stepstep123** [comment] 2021-11-22 09:16
> `def encode2nv12(gpuID, img_tensors, encFilePath, dstFilePath):
> 
> ```
> dstFile = open(dstFilePath, "wb")
> 
> w, h = 720, 1280
> 
> res = str(w) + 'x' + str(h)
> # Encoded video frame
> encFrame = np.ndarray(shape=(0), dtype=np.uint8)
> surface_rgb = nvc.Surface.Make(nvc.PixelFormat.RGB, w, h, gpuID)
> 
> # Surface converters
> nvUpl = nvc.PyFrameUploader(w, h, nvc.PixelFormat.RGB, gpuID)
> to_rgb = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.NV12, nvc.PixelFormat.RGB, gpuID)
> to_yuv = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
> to_nv12 = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
> nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': res, 'bitrate': '10M'}, gpuID)
> 
> # Colorspace conversion contexts.
> # Here we use them just for illustration purposes.
> cc1 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_709,
>                                       nvc.ColorRange.JPEG)
> cc2 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
>                                       nvc.ColorRange.MPEG)
> 
> for img_tensor in img_tensors:
>     
>     img_tensor.resize_(3, h, w)
>     img_tensor *= 255
>     #print(img_tensor)
>     #img_tensor = torch.squeeze(img_tensor, 0)
>     #img_tensor = img_tensor.mul(255).permute(1,2,0)
>     img_tensor = img_tensor.type(dtype=torch.uint8)
>     surface_rgb.PlanePtr().Import(img_tensor.data_ptr(), w * 3, gpuID)
>     
>     surface_yuv = to_yuv.Execute(surface_rgb, cc2)
>     surface_nv12 = to_nv12.Execute(surface_yuv, cc2)
> 
>     # Encode
>     success = nvEnc.EncodeSingleSurface(surface_nv12, encFrame)
>     if success:
>         encByteArray = bytearray(encFrame)
>         dstFile.write(encByteArray)
> while True:
>     success = nvEnc.FlushSinglePacket(encFrame)
>     if (success):
>         encByteArray = bytearray(encFrame)
>         dstFile.write(encByteArray)
>     else:
>         break`
> ```
> 
> i used the code to decoder imge tensor to .nv12 file and then use ffmpeg trans to .mp4.
> 
> get two question:
> 
> 1. the .mp4 file is cololess, only black and whihe.
> 2. the .mp4 file have with*3 pitch
> 
> ![color](https://user-images.githubusercontent.com/43130195/142752160-788614ab-7fff-4f0a-bbcc-b0bf650cf28c.jpg) ![colorfor](https://user-images.githubusercontent.com/43130195/142752163-c7a6b83f-af90-4fbd-9f66-53d18ac60694.jpg)
> 
> could you please give me some suggestion ,thank you so much.

here, i already tried the step 1, but get black-white and much pitch video.
by the way, i didnot modified the function name and then i tried your way to encoded in YUV444

**Comment by rarzumanyan** [comment] 2021-11-22 09:24
@stepstep123 

In that case the only advice I can give is to go through your pipeline step-by-step visually inspecting your video frames.

First thing to do is to investigate what pixel format does your NN expect, is it planar or interleaved RGB.

Then I'd visualize frames as they go through pipeline with OpenCV (see example [here](https://github.com/NVIDIA/VideoProcessingFramework/issues/269)).

**Comment by stepstep123** [comment] 2021-11-22 10:20
> @stepstep123
> 
> > `def encode2nv12(gpuID, img_tensors:list, encFilePath, dstFilePath)`
> 
> From the function name I assume that your encoder is configured to take NV12 input surfaces but you actually give it YUV444 surfaces to encode.
> 
> These two formats have same Y plane layout, that's why your black and white component is fine. Also, YUV444 takes more place in memory then NV12 and because of that encoder doesn't cause memory access violation errors. However, U and V planes layout is different between NV12 and YUV444 which is the reason your video has broken colors.
> 
> There are 2 ways to address this:
> 
> 1. Convert RGB > YUV420, then YUV420 > NV12, then give NV12 surface to encoder.
> 2. Configure your encoder to accept YUV444 frames when you create it:
> 
> ```python
> # These encoding parameters are for illustration purposes. 
> # Use your actual parameters.
> opts = {
>   'preset': 'P4', 
>   'tuning_info': 'high_quality', 
>   'codec': 'h264', 
>   's': '720x1280', 
>   'bitrate': '10M'
> }
> 
> # Note that you need to pass nvc.PixelFormat.YUV444 to encoder constructor.
> # By default nvc.PixelFormat.NV12 is used.
> self.nvEnc = nvc.PyNvEncoder(opts, gpu_id, nvc.PixelFormat.YUV444)
> ```
> 
> P. S.
> 
> Please note that YUV444 decoding support is not very common among consumer electronic devices. If you plan to use your code in production and deliver video after ML inference to customers, I recommend to stick to "usual" `PyNvEncoder` settings and follow path 1.
> 
> If this program is for research / development or just your own internal use, videos encoded in YUV444 format are perfectly fine.



> @stepstep123
> 
> > `def encode2nv12(gpuID, img_tensors:list, encFilePath, dstFilePath)`
> 
> From the function name I assume that your encoder is configured to take NV12 input surfaces but you actually give it YUV444 surfaces to encode.
> 
> These two formats have same Y plane layout, that's why your black and white component is fine. Also, YUV444 takes more place in memory then NV12 and because of that encoder doesn't cause memory access violation errors. However, U and V planes layout is different between NV12 and YUV444 which is the reason your video has broken colors.
> 
> There are 2 ways to address this:
> 
> 1. Convert RGB > YUV420, then YUV420 > NV12, then give NV12 surface to encoder.
> 2. Configure your encoder to accept YUV444 frames when you create it:
> 
> ```python
> # These encoding parameters are for illustration purposes. 
> # Use your actual parameters.
> opts = {
>   'preset': 'P4', 
>   'tuning_info': 'high_quality', 
>   'codec': 'h264', 
>   's': '720x1280', 
>   'bitrate': '10M'
> }
> 
> # Note that you need to pass nvc.PixelFormat.YUV444 to encoder constructor.
> # By default nvc.PixelFormat.NV12 is used.
> self.nvEnc = nvc.PyNvEncoder(opts, gpu_id, nvc.PixelFormat.YUV444)
> ```
> 
> P. S.
> 
> Please note that YUV444 decoding support is not very common among consumer electronic devices. If you plan to use your code in production and deliver video after ML inference to customers, I recommend to stick to "usual" `PyNvEncoder` settings and follow path 1.
> 
> If this program is for research / development or just your own internal use, videos encoded in YUV444 format are perfectly fine.

**i tyied the first way, because we used for client. please correct me if the code have problem. thank you so much.** 

`
def encode2nv12(gpuID, img_tensors:list, encFilePath, dstFilePath):


    dstFile = open(dstFilePath, "wb")

    w, h = 720, 1280

    res = str(w) + 'x' + str(h)
    encFrame = np.ndarray(shape=(0), dtype=np.uint8)

    to_rgb = nvc.PySurfaceConverter(w, h, nvc.RGB_PLANAR, nvc.PixelFormat.RGB, gpu_id)
    to_yuv = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.RGB, nvc.PixelFormat.YUV420, gpuID)
    to_nv12 = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.YUV420, nvc.PixelFormat.NV12, gpuID)
    to_yuv444 = nvc.PySurfaceConverter(w, h, nvc.PixelFormat.RGB_PLANAR, nvc.PixelFormat.YUV444, gpuID)
    nvEnc = nvc.PyNvEncoder({'preset': 'hq', 'codec': 'h264', 's': res}, gpuID)

    # Colorspace conversion contexts.
    # Here we use them just for illustration purposes.
    cc1 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_709,
                                          nvc.ColorRange.JPEG)
    cc2 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                          nvc.ColorRange.MPEG)
    for img_tensor in img_tensors:

        #1 get img_tensor of frame
        img_tensor = img_tensor[0]  # img_tensor:[c, h, w] [3, 720, 1280], img_tensors:[batch, c, h, w][1, 3, 720, 1280]
        img_tensor = img_tensor.permute(1,2,0) #[h, w, c] type(img_tensor) == RGB
        img_tensor = torch.multiply(img_tensor, 255.0)

        # 2 change tensor type
        img_tensor = img_tensor.type(dtype=torch.cuda.uint8)

        #3 make nvc.PixelFormat.RGB
        surface_rgb = nvc.Surface.Make(nvc.PixelFormat.RGB, w, h, gpuID)
        surface_rgb.PlanePtr().Import(img_tensor.data_ptr(), w, gpuID)

        #4 Colorspace conversion contexts.
        cc2 = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                              nvc.ColorRange.MPEG)

        #5 Convert to nv12

        surface_rgb = to_yuv.Execute(surface_rgb, cc2) #yuv420
        surface_yuv = to_nv12.Execute(surface_rgb, cc2) #nv12

        #6 encode
        success = nvEnc.EncodeSingleSurface(surface_yuv, encFrame)
        if success:
            encByteArray = bytearray(encFrame)
            dstFile.write(encByteArray)


`

**Comment by rarzumanyan** [comment] 2021-11-22 10:26
@stepstep123 

I can't reproduce this on my side because I don't have an access to your NN and bandwidth to take this up.
Please follow the steps I've described in previous response. Inspect your NN input and output frames with OpenCV.

Once you get Surface without any visual artifacts, it will be very easy to encode it.

**Comment by stepstep123** [comment] 2021-11-23 08:45
> @stepstep123
> 
> I can't reproduce this on my side because I don't have an access to your NN and bandwidth to take this up. Please follow the steps I've described in previous response. Inspect your NN input and output frames with OpenCV.
> 
> Once you get Surface without any visual artifacts, it will be very easy to encode it.

thank you brother, the problem is solved. 

now, when we local have a .mp4 file, we use vpf to decode -> NN model -> VFP encode -> yuv444 file. it's perfect.
but when we have a RTMP stream or a flv file, can the vpf do decode?  
`nvDec = nvc.PyNvDecoder(input_video, gpu_id)`

if can't. please give me some suggestions.

thank you

**Comment by stepstep123** [comment] 2021-11-23 10:05
> @stepstep123
> 
> I can't reproduce this on my side because I don't have an access to your NN and bandwidth to take this up. Please follow the steps I've described in previous response. Inspect your NN input and output frames with OpenCV.
> 
> Once you get Surface without any visual artifacts, it will be very easy to encode it.

**https://github.com/NVIDIA/VideoProcessingFramework/issues/284#issuecomment-975376161**

**Comment by rarzumanyan** [comment] 2021-11-23 10:06
@stepstep123 
You're welcome.

>when we have a RTMP stream or a flv file, can the vpf do decode?

Yes it can. There are 2 possible ways to do this:

1. Just pass RTMP URL to `PyNvDecoder` constructor. VPF relies on libavformat and libavcodec libraries to extract video stream from source, it shall work because these libraries support variety of network protocols.
2. Spawn FFMpeg sub-process to extract video stream from network source and communicate with VPF through pipe. 
 
I recommend you to use №2 in production, it's more robust. FFMpeg application is mature and it handles network connection problems better then built-in VPF demuxer. I'm not experienced with media streaming so I was able to implement simple demuxer with help of libavformat / libavcodec libraries. It works nice and stable with local files, but it's not as good with network input as FFMpeg is. 

Also, I've just merged a feature branch which improves approach №2 support, please check out `master` ToT. Now there's a dedicated sample `SampleDecodeRTSP.py` which shall be relevant to RTMP as well.

P. S.
Take a look at #257, it covers the topic of how to decode as many RTSP streams as possible, it may be useful.

**Comment by stepstep123** [comment] 2021-11-23 10:09
> @stepstep123 You're welcome.
> 
> > when we have a RTMP stream or a flv file, can the vpf do decode?
> 
> Yes it can. There are 2 possible ways to do this:
> 
> 1. Just pass RTMP URL to `PyNvDecoder` constructor. VPF relies on libavformat and libavcodec libraries to extract video stream from source, it shall work because these libraries support variety of network protocols.
> 2. Spawn FFMpeg sub-process to extract video stream from network source and communicate with VPF through pipe.
> 
> I recommend you to use №2 in production, it's more robust. FFMpeg application is mature and it handles network connection problems better then built-in VPF demuxer. I'm not experienced with media streaming so I was able to implement simple demuxer with help of libavformat / libavcodec libraries. It works nice and stable with local files, but it's not as good with network input as FFMpeg is.
> 
> Also, I've just merged a feature branch which improves approach №2 support, please check out `master` ToT. Now there's a dedicated sample `SampleDecodeRTSP.py` which shall be relevant to RTMP as well.
> 
> P. S. Take a look at #257, it covers the topic of how to decode as many RTSP streams as possible, it may be useful.

fantastic! this feeling is great! we are online together and reply in time.
thank your help and your VPF is nice, i will recommend it to my team.

**Comment by stepstep123** [comment] 2021-11-24 13:04
> Collaborator
1. Just pass RTMP URL to PyNvDecoder constructor. VPF relies on libavformat and libavcodec libraries to extract video stream from source, it shall work because these libraries support variety of network protocols.

here is my code:
`

class Reader(object):
    def __init__(self, input_video, gpuID):
        self.gpuID = gpuID
        self.input_video = input_video
        cuda.init()
        self.nvDec = nvc.PyNvDecoder(self.input_video, self.gpuID) # load rtmp url

        self.target_w = self.nvDec.Width()
        self.target_h = self.nvDec.Height()

        self.to_yuv = nvc.PySurfaceConverter(self.nvDec.Width(), self.nvDec.Height(),
                                        nvc.PixelFormat.NV12, nvc.PixelFormat.YUV420,
                                        self.gpuID)
        self.to_dim = nvc.PySurfaceResizer(self.target_w, self.target_h, nvc.PixelFormat.YUV420,
                                      self.gpuID)
        self.to_rgb = nvc.PySurfaceConverter(self.target_w, self.target_h,
                                        nvc.PixelFormat.YUV420, nvc.PixelFormat.RGB,
                                        self.gpuID)
        self.to_pln = nvc.PySurfaceConverter(self.target_w, self.target_h, nvc.PixelFormat.RGB,
                                        nvc.PixelFormat.RGB_PLANAR, self.gpuID)
        # Use most widespread bt601 and mpeg just for illustration purposes.
        self.cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601,
                                                 nvc.ColorRange.MPEG)
        self.rec = [None] * 4

    def decode_to_tensor(self):

        # Decode 1 compressed video frame to CUDA memory.
        self.nv12_surface = self.nvDec.DecodeSingleSurface()
        if self.nv12_surface.Empty():
            return True

        #2  Convert from NV12 to YUV420.
        # This extra step is required because not all NV12 -> RGB conversions
        # implemented in NPP support all color spaces and ranges.
        yuv420 = self.to_yuv.Execute(self.nv12_surface, self.cc_ctx)

        #3  Downscale YUV420.
        yuv_small = self.to_dim.Execute(yuv420)

        #4  Convert from YUV420 to interleaved RGB.
        rgb24_small = self.to_rgb.Execute(yuv_small, self.cc_ctx)
        if rgb24_small.Empty():
            print('Can not convert yuv420 -> rgb')

        #5 Convert to planar RGB.
        rgb24_planar = self.to_pln.Execute(rgb24_small, self.cc_ctx)

        # Export to PyTorch tensor
        surf_plane = rgb24_planar.PlanePtr()
        img_tensor = pnvc.makefromDevicePtrUint8(surf_plane.GpuMem(),
                                                 surf_plane.Width(),
                                                 surf_plane.Height(),
                                                 surf_plane.Pitch(),
                                                 surf_plane.ElemSize())

        img_tensor.resize_(1, 3, self.target_h, self.target_w) #[batch_size, 3, h, w]
        img_tensor = img_tensor.type(dtype=torch.cuda.FloatTensor)
        img_tensor = torch.divide(img_tensor, 255.0)
        self.img_tensor = img_tensor
        return False


`
and then

`

 reader = Reader('rtmp url', 0)
 while True:
     flag = reader.infer_on_video()
     if  flag:
          break
    res =  model(reader.img_tensor) # cnn model

`
the code have any proble, i want to load rtmp url and Export to PyTorch tensor , finally cnn model inference
i did it ,but the res is break.

**Closed** 2021-11-26 07:13 UTC
