### ISSUE TITLE
does not throw an exception when the camera is disconnected from the Internet

### ISSUE THREAD

**Issue by scai2013** [NVIDIA/VideoProcessingFramework#280] opened 2021-11-16 09:23 UTC
hi, i found out the program does not throw an exception when the camera is disconnected from the Internet, and staying at statement
```
 logger.error('one more frames begining')
 rawSurface = nvDec.DecodeSingleSurface() 
logger.error('after frames ')# didnot  excute here
```
please help!!!

**Comment by rarzumanyan** [comment] 2021-11-24 09:17
Hi @scai2013 
Apologies for the delayed response.

Please take a look at dedicated `SampleDecodeRTSP.py` which was recently pushed to `master` branch.

I recommend you to follow it and use FFMpeg sub-process to extract video stream from network, FFMpeg app handles network issues better then built-in VPF demuxer.

Please note, that this FFMpeg sub-process doesn't influence performance because the video stream extraction is done on CPU anyway. The actual decoding is still performed by Nvdec.

If you have issues with mentioned sample, please use #257 for that. I'm closing this issue because it's going to be a duplicate of #257.

**Closed by rarzumanyan** 2021-11-24 09:17 UTC
