### ISSUE TITLE
Build error！

### ISSUE THREAD

**Issue by Waxyoung** [NVIDIA/VideoProcessingFramework#23] opened 2020-03-30 12:18 UTC
hello，i get a problem，please give me some advise，thank you！

![image](https://user-images.githubusercontent.com/26435611/77911566-9ad41180-72c3-11ea-825f-7beb4dd6a8ed.png)

**Comment by Waxyoung** [comment] 2020-03-30 12:20
Cmake is 。。。。。
![image](https://user-images.githubusercontent.com/26435611/77911761-f2727d00-72c3-11ea-922f-43014ea6b8ad.png)

**Comment by rarzumanyan** [comment] 2020-03-30 12:43
Hi @Waxyoung 
Compiler can't find NPP headers.
Easiest way to fix it is to find where the `nppi_color_conversion.h` is located and add it to cxxflags.
It should be done automatically but probably CMake struggles to find your CUDA SDK folder. 
BTW How did you install your CUDA SDK?

**Comment by Waxyoung** [comment] 2020-03-30 13:14
cudnn.h   in  /usr/include/   cuda.h  in /usr/include/linux  
so i  use export CXXFLAGS= "-isystem /usr/include/linux -isystem /usr/include"  before Cmake。
Is that ok？

**Comment by Waxyoung** [comment] 2020-03-31 08:37
hello，@rarzumanyan ,when i build use your way,error is ...
![image](https://user-images.githubusercontent.com/26435611/78005275-e9d68100-736d-11ea-8488-0edbaff195e0.png)

**Comment by Waxyoung** [comment] 2020-03-31 08:37
please give me some advise，thank you！

**Comment by rarzumanyan** [comment] 2020-03-31 08:59
Hi @Waxyoung,

Below is how I build VPF for testing on clean linux machines.
Please give it a try and send me CMake configure & output logs if it fails.

P. S.
I'm using Anaconda Python for Pytorch bindings but it shouldn't make a big difference.

FFmpeg build:
```bash
cd ~/Git
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg

mkdir -p $(pwd)/build_x64_release_shared 
./configure \
 --prefix=$(pwd)/build_x64_release_shared \
 --disable-static \
 --disable-stripping \
 --disable-doc \
 --enable-shared
 
make -j -s && make install
```

VPF build:
```bash
# Export paths to Video Codec SDK and FFMpeg
export PATH_TO_SDK=~/Video_Codec_SDK_9.1.23
export PATH_TO_FFMPEG=~/Git/FFmpeg/build_x64_release_shared

# Clone repo and start building process
cd ~/Git
git clone https://github.com/NVIDIA/VideoProcessingFramework.git

# Export path to Cmake:
export PATH=$PATH:/home/rarzumanyan/cmake-3.16.4-Linux-x86_64/bin

# Export path to CUDA compiler (I'm installing drivers from Nvidia site):
export CUDACXX=/usr/local/cuda/bin/nvcc

#Now the VPF build
cd VideoProcessingFramework
export INSTALL_PREFIX=$(pwd)/install
mkdir -p install
mkdir -p build
cd build
cmake .. \
  -DFFMPEG_DIR:PATH="$PATH_TO_FFMPEG" \
  -DVIDEO_CODEC_SDK_DIR:PATH="$PATH_TO_SDK" \
  -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
  -DPYTHON_LIBRARY=/home/rarzumanyan/anaconda3/lib/libpython3.7m.so \
  -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_PREFIX"
make && make install

# Launch samples
cd ~/Git/VideoProcessingFramework/install/bin
export LD_LIBRARY_PATH=$PATH_TO_FFMPEG/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
python3 ./SampleDecode.py
```

**Comment by Waxyoung** [comment] 2020-04-01 04:28
cmake：
![image](https://user-images.githubusercontent.com/26435611/78099301-1218bb00-7414-11ea-9bb1-131c06e4ce02.png)


install succeed：
![image](https://user-images.githubusercontent.com/26435611/78099324-26f54e80-7414-11ea-9bd6-1c9bbaeecb8e.png)

but   when i  run  SampleDecode，error is  ：
![image](https://user-images.githubusercontent.com/26435611/78099360-3bd1e200-7414-11ea-8a55-0494c1e3ca4b.png)

**Comment by rarzumanyan** [comment] 2020-04-01 05:57
Hi @Waxyoung,
Good news that you were able to build it from source.

The error you see (392434440) isn't a CUDA error, the value is outside of the range.
NvDecoder.cpp:574 is where the first call to Video Codec SDK API is made:
```Cpp
cuvidCtxLockCreate(&p_impl->m_ctxLock, cuContext)
```
 It looks like something goes wrong during the libraries loading stage when you run the sample.

Can you run `ldd PyNvCodec.cpython-35m-x86_64-linux-gnu.so` to see what libraries are loaded with the Python module? Also, please upload the output of `nvidia-smi` to see the GPU model and driver version.

**Comment by Waxyoung** [comment] 2020-04-01 06:10
**ldd PyNvCodec.cpython-35m-x86_64-linux-gnu.so**
![image](https://user-images.githubusercontent.com/26435611/78104800-58751680-7422-11ea-9e69-40c765f09de9.png)

**nvidia-smi**
![image](https://user-images.githubusercontent.com/26435611/78104866-7b9fc600-7422-11ea-97af-6ae4d01d4ab2.png)

**Comment by rarzumanyan** [comment] 2020-04-01 06:35
Hi @Waxyoung 

Your driver version is too old, you need to update to 435.21 for SDK 9.1.23.
BTW if you don't have any specific limitations on SW versions I recommend you to update to latest video driver & CUDA SDK.

**Comment by Waxyoung** [comment] 2020-04-01 06:51
thank you very much！
BTW  i want to know  what is SW?  and ,what is video driver? video driver= Video_Codec_SDK_9.1.23 ?

**Comment by rarzumanyan** [comment] 2020-04-01 07:29
Hi @Waxyoung 
SW is software :)

"Video driver" is Nvidia GPU driver. You see it's version in `nvidia-smi` output. It has version 410.79 on your machine.

Video Codec SDK is a set of libraries + header files + samples in C/C++ languages. It's only used by developers who want their application to utilize Nvidia GPUs for video encoding / decoding acceleration. End users don't need the SDK to get applications working properly. 

Please notify if the issue is solved and can be closed.

**Comment by TimVerion** [comment] 2020-04-07 08:07
thank you very much！My graphics driver is really old

**Comment by rarzumanyan** [comment] 2020-04-07 08:21
Hi @TimVerion,

Please update the issue if newer driver solves the problem.
This invalid error code bug is a big headache, I'm trying to track what helps user to solve it.

**Comment by TimVerion** [comment] 2020-04-07 12:17
I did update the driver, but I updated it to[ 430.64](https://www.nvidia.cn/Download/index.aspx?lang=cn). The computer graphics card is in Geforce
GTX1660Ti, then use the[ video_codec_sdk_9.0.20](https://developer.nvidia.com/video-codec-sdk-archive) version.So I can do a good codec.

**Comment by rarzumanyan** [comment] 2020-04-07 12:39
Thank you for the update, I'm glad this is solved.
Closing the issue.

**Closed by rarzumanyan** 2020-04-07 12:39 UTC

**Comment by eagle-ming** [comment] 2023-07-04 15:45
<img width="995" alt="image" src="https://github.com/NVIDIA/VideoProcessingFramework/assets/116535303/c0c1b5e6-cc9f-4ea3-bc7a-cc6bbcd5656f">
when I built VPF,  the cmake always not succeed, how can I fix the issue?
