### ISSUE TITLE
SampleDecodeMultiThread.py not work in win10

### ISSUE THREAD

**Issue by scai2013** [NVIDIA/VideoProcessingFramework#275] opened 2021-11-06 07:07 UTC
i have builded process after  wiki learning，and no errors occurred during compilation. then i run SampleDecode.py to test it's right. the result as picture below：
![image](https://user-images.githubusercontent.com/3307375/140600758-409126bc-1398-43a4-85b5-f85ffedd2bff.png)

however， I run SampleDecodeMultiThread.py and it exited without any err info in decoding statement.  Is my compilation problematic? please help!
```
 def run(self):
        try:
            while True:
                try:
                    self.rawSurface = self.nvDec.DecodeSingleSurface() ### exit without any err info
                    if (self.rawSurface.Empty()):
```
`result
D:\vpf\vpf\install\bin>python SampleDecodeMultiThread.py 0 994.mp4 1
This sample decodes video streams in parallel threads. It does not save output.
GPU-accelerated color conversion and resize are also applied.
This sample may serve as a stability test.
Usage: python SampleDecodeMultiThread.py $gpu_id $input $num_threads
Color space:  ColorSpace.BT_709
Color range:  ColorRange.JPEG

D:\vpf\vpf\install\bin>

`
![image](https://user-images.githubusercontent.com/3307375/140601287-9143c6c0-d7da-4d06-90ae-0b0401ce5e88.png)

**Comment by rarzumanyan** [comment] 2021-11-06 08:23
Hi @scai2013 

The problem is most probably in color conversion, not all combination of color space and color range are supported in NPP yet. A quick way to check would be to comment out couple lines here:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9a1801ffab465a271e32537a775720c9f3b6dfeb/SampleDecodeMultiThread.py#L68-L75

Just hardcode the `BT_601` color space and `MPEG` color range.

**Comment by scai2013** [comment] 2021-11-06 10:10
> Hi @scai2013
> 
> The problem is most probably in color conversion, not all combination of color space and color range are supported in NPP yet. A quick way to check would be to comment out couple lines here:
> 
> https://github.com/NVIDIA/VideoProcessingFramework/blob/9a1801ffab465a271e32537a775720c9f3b6dfeb/SampleDecodeMultiThread.py#L68-L75
> 
> Just hardcode the `BT_601` color space and `MPEG` color range.

HI, i comment out lines and just hardcode the `BT_601` color space and `MPEG` color range like below, but still the same result. 
```
        #cspace, crange = self.nvDec.ColorSpace(), self.nvDec.ColorRange()
        #if nvc.ColorSpace.UNSPEC == cspace:
        #    cspace = nvc.ColorSpace.BT_601
        #if nvc.ColorRange.UDEF == crange:
        #    crange = nvc.ColorRange.MPEG
        cspace, crange = nvc.ColorSpace.BT_601, nvc.ColorRange.MPEG
        self.cc_ctx = nvc.ColorspaceConversionContext(nvc.ColorSpace.BT_601, nvc.ColorRange.MPEG)
        print('Color space: ', str(cspace))
        print('Color range: ', str(crange))
```

**Comment by rarzumanyan** [comment] 2021-11-06 10:44
Thanks for the update, I'll do a triage on my machine and will update you later as I find something.

**Comment by rarzumanyan** [comment] 2021-11-06 10:55
@scai2013 

I think I've found the root cause, pointer was de-referenced without nullptr check.
Please check `issue_275` branch.

**Comment by scai2013** [comment] 2021-11-07 09:46
> @scai2013
> 
> I think I've found the root cause, pointer was de-referenced without nullptr check. Please check `issue_275` branch.

it works by  `issue_275` branch. very thankful!!!

**Comment by rarzumanyan** [comment] 2021-11-07 09:53
@scai2013 

Great, thanks for the update.
Merging to `master` and closing issue as resolved.

**Closed by rarzumanyan** 2021-11-07 09:53 UTC
