### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by TimVerion** [NVIDIA/VideoProcessingFramework#26] opened 2020-04-07 06:15 UTC
Video_Codec_SDK_9.0.20
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
ffmpeg 4.2.1
No problem with compilation
But when I run: python SampleDecode.py
 it says:
Traceback (most recent call last):
  File "SampleDecode.py", line 24, in <module>
    nvDec = nvc.PyNvDecoder(encFile, gpuID)
RuntimeError: xxx/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:568
CUDA error with code -2072787712
No error string available

**Comment by rarzumanyan** [comment] 2020-04-07 06:36
Hi @TimVerion 

This issue is duplicate of https://github.com/NVIDIA/VideoProcessingFramework/issues/23

**Closed by rarzumanyan** 2020-04-07 06:36 UTC
