### ISSUE TITLE
PytorchNvCodec uses GPU 0 memory despite target GPU being set as 1

### ISSUE THREAD

**Issue by gaosanyuan** [NVIDIA/VideoProcessingFramework#199] opened 2021-04-28 03:02 UTC
We found that PyNvDecoder will always use gpu 0, and actually we just want it to work on gpu 1 (parameter gpu_id is assigned to be 1).
Why and how to fix it, thanks

**Comment by rarzumanyan** [comment] 2021-04-28 07:52
Hello @gaosanyuan 

I've just checked the `master` ToT and on my machine. `PyNvDecoder` uses different GPUs depending on CLI settings.

`python3.9 SampleDecode.py 1 big_buck_bunny_1080p_h264.mov out.nv12` uses GPU 1:
```cmd
C:\Users\rarzumanyan>nvidia-smi dmon
# gpu   pwr gtemp mtemp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     C     %     %     %     %   MHz   MHz

    0    60    52     -     1     0     0     0  9251  1710
    1    38    38     -     5     0     0     2  6500  1620
    0    99    52     -     1     0     0     0  9251  1710
    1    38    38     -    13     2     0    23  6500  1620
    0    99    52     -     1     0     0     0  9251  1710
    1    38    38     -    14     2     0    23  6500  1620
    0    99    53     -     0     0     0     0  9251  1710
    1    38    38     -    13     2     0    24  6500  1620

```
while `python3.9 SampleDecode.py 0 big_buck_bunny_1080p_h264.mov out.nv12` uses GPU 0:
```cmd
C:\Users\rarzumanyan>nvidia-smi dmon
# gpu   pwr gtemp mtemp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     C     %     %     %     %   MHz   MHz

    0    79    52     -     3     0     0    10  9251  1710
    1     1    36     -     0     0     0     0   405   300
    0   103    52     -     9     1     0    54  9251  1710
    1     2    36     -     0     0     0     0   405   300
    0   103    52     -     9     1     0    54  9251  1710
    1     2    36     -     0     0     0     0   405   300
    0   103    53     -     9     1     0    49  9251  1710
    1     2    36     -     0     0     0     0   405   300
```

Hence if this problem exists it's specific to some particular HW & SW combination.
Please provide your Video Codec SDK, driver, CUDA & python versions, your OS and try mentioned sample as shown above.

**Comment by liuyuhao** [comment] 2021-04-29 03:17
Hi，@rarzumanyan @gaosanyuan 
        The following is the environment and code in which the problem is described.
- **### environment**

```
PyTorch version: 1.7.0+cu110
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.14.4

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.0+cu110
[pip3] torchvision==0.8.0
```

- **### code**

```
import torch
import PyNvCodec as nvc
import PytorchNvCodec as pnvc


def decode_video(local_video_file, gpu_id):
    nvDec = nvc.PyNvDecoder(local_video_file, gpu_id)
    to_rgb = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.NV12,  nvc.PixelFormat.RGB, gpu_id)
    to_planar = nvc.PySurfaceConverter(nvDec.Width(), nvDec.Height(), nvc.PixelFormat.RGB, nvc.PixelFormat.RGB_PLANAR,
                                       gpu_id)
    while True:
        # Obtain NV12 decoded surface from decoder;
        rawSurface = nvDec.DecodeSingleSurface()
        if (rawSurface.Empty()):
            break
        # Convert to RGB interleaved;
        rgb_byte = to_rgb.Execute(rawSurface)
        # Convert to RGB planar because that's what to_tensor + normalize are doing;
        rgb_planar = to_planar.Execute(rgb_byte)
        # Create torch tensor from it and reshape because
        # pnvc.makefromDevicePtrUint8 creates just a chunk of CUDA memory
        # and then copies data from plane pointer to allocated chunk;
        surfPlane = rgb_planar.PlanePtr()
        surface_tensor = pnvc.makefromDevicePtrUint8(surfPlane.GpuMem(), surfPlane.Width(),
                                                     surfPlane.Height(),
                                                     surfPlane.Pitch(), surfPlane.ElemSize())
        surface_tensor.resize_(3, 2048, 2448)

if __name__ == '__main__':
    video_file = “path_to_video_file”
    gpu_id = 1
    decode_video(video_file, gpu_id)
```

**Comment by rarzumanyan** [comment] 2021-04-29 08:57
Hi @liuyuhao 
You choose GPU 1 in your script:
```python
if __name__ == '__main__':
    video_file = “path_to_video_file”
    gpu_id = 1
    decode_video(video_file, gpu_id)
```

Makes total sense in combination with your `nvidia-smi` screenshot (?)

**Comment by liuyuhao** [comment] 2021-04-29 09:30
@rarzumanyan 
Yes, I did choose GPU 1, I am not sure why GPU 0 also has some video memory used，and I'm not running any other tasks.

**Comment by rarzumanyan** [comment] 2021-04-29 10:31
@liuyuhao 

In your use scenario, 2 SW components are using CUDA runtime API: 
- Pytorch 
- VPF
 
1 SW component uses CUDA driver API: 
- VPF

My advice is to isolate them and investigate step by step: run one of VPF samples that doesn't involve PyTorch on GPU 1 and see if GPU 0 memory is significantly used. If it does - there are some issues on VPF side.

**Comment by liuyuhao** [comment] 2021-04-29 10:54
@rarzumanyan 
I tested it with the following code，GPU 0 memory is used sparingly.
![image](https://user-images.githubusercontent.com/83384781/116539828-f08e4980-a91b-11eb-9957-7b387123e0c4.png)

```
import PyNvCodec as nvc

def decode_video(local_video_file, gpu_id):
    nvDec = nvc.PyNvDecoder(local_video_file, gpu_id)
    while True:
        # Obtain NV12 decoded surface from decoder;
        rawSurface = nvDec.DecodeSingleSurface()
        if (rawSurface.Empty()):
            break

if __name__ == '__main__':
    video_file = “path_to_video_file”
    gpu_id = 1
    decode_video(video_file, gpu_id)
```

I use PytorchNvCodec to run, GPU 0 with a lot of memory.
![image](https://user-images.githubusercontent.com/83384781/116539958-1f0c2480-a91c-11eb-86a8-61003a238319.png)

**Comment by rarzumanyan** [comment] 2021-04-29 11:22
Thanks for the update @liuyuhao 

Does this behavior reproduces if you use PyTorch without VPF? 
I want to understand if the excessive memory consumption is specific to PyTorch<->VPF handshake or it's usual PyTorch behavior.

**Comment by liuyuhao** [comment] 2021-04-29 11:35
In my past use of PyTorch, I haven't foundexcessive memory usage. I'm not sure if you can reproduce this situation, maybe there's something wrong with my build.

**Comment by rarzumanyan** [comment] 2021-04-29 12:23
@liuguilin1225 

It's not the first time I see users face similar issues.
I'll investigate on my machine and will update as I find something.

**Comment by rarzumanyan** [comment] 2021-04-29 18:30
@liuguilin1225 
After triage on my machine with 2 GPUs
```cmd
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 457.30       Driver Version: 457.30       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3080   WDDM  | 00000000:01:00.0 Off |                  N/A |
|  0%   52C    P8    25W / 320W |    926MiB / 10240MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 5000    WDDM  | 00000000:02:00.0 Off |                  Off |
| 35%   36C    P8     2W / 230W |    214MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

I see that running a PyTorch sample like follows
```cmd
python.exe SamplePyTorch.py 1 big_buck_bunny_1080p_h264.mov out.h264
```
consumes ~300 Mb on GPU0 and ~900 Mb on GPU1 which is target.
Please note that even in idle OS state, 900+Mb of GPU0 memory is occupied.
Can you reproduce this on your machine and share the results?

**Comment by lferraz** [comment] 2021-04-30 15:29
hi guys @rarzumanyan @liuguilin1225,

I think it is related (sorry if it is not), 2 years ago I created an issue in [ pytorch](https://github.com/pytorch/pytorch/issues/13119) for something related and basically few days ago they told me that it is not happening now.

**Comment by rarzumanyan** [comment] 2021-04-30 16:17
Thanks for the update, @lferraz 

I've seen a similar issue couple times although I can't reproduce it to some kind of significant extent in my environment.
There's some GPU0 memory utilization which happens all the time although the scale isn't that worrying.
When I was implementing the PyTorch <-> VPF handshake, I've delve a little bit into PyTorch memory allocation code and didn't understand too much, it's complicated. Honestly I'm running out of depth here due to lack of in-depth PyTorch knowledge.

**Comment by vtpl1** [comment] 2021-05-04 08:57
@rarzumanyan ,
I have got similar issue. Running `SampleDecodeMultiThread.py` would produce similar behaviour. There is no PyTorch. (Sorry if the comment does not match the issue Heading)
Let me try to explain:

**Possible reason 1:**
Let us consider the line:

https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/src/PyNvCodec.cpp#L272-L273

The `Surface::Make(outputFormat)` will be allocated in default context, i.e. context of GPU0.
The context management code is inside `upResizer`.

https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/TC/src/Tasks.cpp#L918-L919

**Possible reason 2:**
The `NppLock lock(nppCtx);` needs a CUDA context which is getting set later by this code. `CudaCtxPush ctxPush(cu_ctx);`

https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/TC/src/Tasks.cpp#L918-L919

So the `NppLock lock(nppCtx);` operates on default context, i.e. context of GPU0.

**Possible solution reason 2:**
I think the proper order would be:

`CudaCtxPush ctxPush(cu_ctx);`
`NppLock lock(nppCtx);`

**Possible solution reason 1:**
Bring the context management where at least one surface is getting created.
i.e. in the file: 
[PyNvCodec.cpp](https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/src/PyNvCodec.cpp)

**Comment by rarzumanyan** [comment] 2021-05-04 10:14
Thanks for the detailed reply, @vtpl1 

Regarding the **possible reason 1**:
If you take a closer look into `Surface::Make(outputFormat)`, it calls default constructor for given format:
https://github.com/NVIDIA/VideoProcessingFramework/blob/10dc42a5307627984ed06febfd4c5435ff91accb/PyNvCodec/TC/src/MemoryInterfaces.cpp#L398-L417

Let's take a look at default `SurfaceNV12` ctor for example:
https://github.com/NVIDIA/VideoProcessingFramework/blob/10dc42a5307627984ed06febfd4c5435ff91accb/PyNvCodec/TC/src/MemoryInterfaces.cpp#L518
It will basically call a default constructor for `SurfaceNV12::plane`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/10dc42a5307627984ed06febfd4c5435ff91accb/PyNvCodec/TC/src/MemoryInterfaces.cpp#L241

This constructor doesn't allocate CUDA memory.

So the CUDA context doesn't matter too much here because no CUDA API calls are done.
`Surface::Make(outputFormat)` will basically return "empty" NV12 `Surface` to Python with all dimensions set to zero and no memory allocated.

Regarding the **possible reason 2:**
`NppLock` is a legacy structure which was used before the stream managed NPP API functions were released as part of CUDA 10.1 IIRC. Now it's completely redundant and it doesn't serve any particular purpose. The only thing it did it was synchronizing CUDA stream upon destructor call.

Regarding the `NppStreamContext` structure - it doesn't have a CUDA context as structure field, only device id. Below is the function which sets this structure up:
https://github.com/NVIDIA/VideoProcessingFramework/blob/10dc42a5307627984ed06febfd4c5435ff91accb/PyNvCodec/TC/src/NppCommon.cpp#L10-L39


P. S.
I've created `issue_199` branch in which I've removed this structure at all. 
Please check it out if you like and thank you for bringing this up.

**Comment by vtpl1** [comment] 2021-05-04 15:51
@rarzumanyan ,
Are you sure `cudaStreamSynchronize(ctx.hStream); ` is not required?
https://github.com/NVIDIA/VideoProcessingFramework/blob/edb7d8fc4721eef490f116b942a6d9e384110617/PyNvCodec/TC/src/NppCommon.cpp#L43

**Comment by rarzumanyan** [comment] 2021-05-05 09:01
@vtpl1 

> Are you sure `cudaStreamSynchronize(ctx.hStream); ` is not required?

I think it shall not cause issues because stream is in-order queue in which tasks (e. g. CUDA kernel execution or data copy) are put. Since VPF follows one device - one stream approach, all the GPU tasks will be executed in order and every time we interchange data with GPU we synchronize the stream.

**Comment by vtpl1** [comment] 2021-05-05 18:28
@rarzumanyan ,
I don't think it is an acceptable proposition. The decoded and resized gpu memory is generally passed to another library whose stream and context internally managed by the library. This stream and context is not same as that of VPF.

**Comment by rarzumanyan** [comment] 2021-05-05 20:24
Hi @vtpl1 

>I don't think it is an acceptable proposition. The decoded and resized gpu memory is generally passed to another library whose stream and context internally managed by the library

Please take a closer look at the function which sets up NPP managed context, it takes given CUDA context and stream.
So I'm pretty sure NPP uses given stream to launch underlying CUDA kernels because this is the sole purpose of stream management:
https://github.com/NVIDIA/VideoProcessingFramework/blob/edb7d8fc4721eef490f116b942a6d9e384110617/PyNvCodec/TC/src/NppCommon.cpp#L10-L39

Beside that I've added NVTX markers support to `nvtx_support` branch so please check it out if you like.

I've also added couple `cuStreamSynchronize()` calls although they are redundant because they affect DtoD memory transfer. More elegant approach to this would be to augment `Task` parent class and introduce 2 sub-classes for blocking and non-blocking tasks. Those tasks which runs on GPU exclusively shall be non-blocking since CUDA stream is in-order.

P. S.
This is what I see in Nsight as I profile `SampleDemuxDecode` (I've changed it slightly to use NPP nv12->yuv420 conversion):

![Capture](https://user-images.githubusercontent.com/45193474/117203122-53d61b00-adf7-11eb-9e63-7c7facf2c7e1.JPG)

**Comment by vtpl1** [comment] 2021-05-06 18:00
Hi @rarzumanyan, thank you for the nvtx_support branch, while investigating the stream synchronize issue another issue #204 came up.

**Comment by rarzumanyan** [comment] 2021-05-12 12:30
@vtpl1

Please confirm if this is resolved and code from nvtx_support can be merged to master.

**Comment by vtpl1** [comment] 2021-05-12 16:17
@rarzumanyan,
Could not check the PytorchnvCodec but issue #204 is solved. I think it is good to merge the `nvtx_support` to `master`

**Comment by rarzumanyan** [comment] 2021-05-12 16:27
Closing as resolved.

**Closed by rarzumanyan** 2021-05-12 16:27 UTC
