### ISSUE TITLE
Decode RTSP stream

### ISSUE THREAD

**Issue by roflcoopter** [NVIDIA/VideoProcessingFramework#4] opened 2019-12-27 16:07 UTC
Im trying to use this to decode an RTSP stream from an IP camera.
I modified the example to use the RTSP url but it seems to only accept files. Is it possible to decode RTSP streams somehow?
```
import PyNvCodec as nvc

encFile = "rtsp://user:pass@hostname:554/Streaming/Channels/101/"
decFile = open("output.nv12", "wb")

nvDec = nvc.PyNvDecoder(encFile, 0)

while True:
    rawFrame = nvDec.DecodeSingleFrame()
    # Decoder will return zero-size frame if input file is over;
    if not (rawFrame.size):
        break

    frameByteArray = bytearray(rawFrame)
    decFile.write(frameByteArray)
```
The error message is:
```
Decoding on GPU 0
rtsp://user:pass@hostname:554/Streaming/Channels/101/
[-----] General error -1330794744 at line 178 in file /VideoProcessingFramework/PyNvCodec/TC/src/FFmpegDemuxer.cpp
[-----] No AVFormatContext provided.
Traceback (most recent call last):
  File "vpf_test.py", line 7, in <module>
    nvDec = nvc.PyNvDecoder(encFile, 0)
RuntimeError: CUDA error: CUDA_ERROR_INVALID_SOURCE
```

**Comment by rarzumanyan** [comment] 2019-12-27 21:52
Hi,
VPF uses FFMpeg for demuxing so it supports rtsp as long as ffmpeg build you’re using supports it.

To isolate VPF bugs from possible ffmpeg bugs, can you please provide the following information:
1) what codec is used by rtsp stream?
2) can you decode it with ffmpeg application?

**Comment by roflcoopter** [comment] 2019-12-27 22:00
Hi!

The stream is H264.
I am running FFMPEG in a docker container since earlier, and i can succesfully decode the stream using this command:
```
ffmpeg -hwaccel cuvid -c:v h264_cuvid -vsync 0 -rtsp_transport tcp -i rtsp://user:pass@host:554/Streaming/Channels/101/ -vcodec h264_nvenc output.mp4
```

To build VPF inside my container i manually downloaded the Video Codec SDK and added the follwing to my Dockerfile
```
ADD /docker/docker-gpu/Video_Codec_SDK_9.1.23.zip /
RUN apt-get update &&  apt-get install -y --no-install-recommends unzip cmake git && \
    unzip -q Video_Codec_SDK_9.1.23.zip -d /usr/local/lib/ && \
    rm Video_Codec_SDK_9.1.23.zip && \
    cd / && \
        git clone https://github.com/NVIDIA/VideoProcessingFramework.git && \
        cd VideoProcessingFramework && \
        mkdir build && \
        cd build && \
        cmake \
            -DFFMPEG_DIR:PATH="/usr/local/ffmpeg/bin" \
            -DVIDEO_CODEC_SDK_DIR:PATH="/usr/local/lib/Video_Codec_SDK_9.1.23" \
            -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
            -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/vpf"\ 
            .. &&\
        make -j$(nproc) && \
        make install && \
    apt-get purge --autoremove -y unzip curl git
```
Is this the correct way of building on Ubuntu?

**Comment by rarzumanyan** [comment] 2019-12-28 06:53
Hi,
VPF creates format context with default flags and that’s probably the reason it can’t decode your stream.

Can you please try to use the same ffmpeg command above but without -rtsp_transport tcp?

If it fails to decode, I’ll try to modify the VPF sources and add dictionary option support.

**Comment by roflcoopter** [comment] 2019-12-28 08:49
It works without -rtsp_transport
`ffmpeg -hwaccel cuvid -c:v h264_cuvid -vsync 0 -i rtsp://user:pass@Host:554/Streaming/Channels/101/ -vcodec h264_nvenc output.mp4 `

**Comment by roflcoopter** [comment] 2019-12-28 09:21
I'm not sureif this helps, but this is the output of `nvidia-smi` inside my container

```
Sat Dec 28 09:20:17 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  On   | 00000000:01:00.0  On |                  N/A |
| 23%   32C    P8    16W / 120W |      0MiB /  5942MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
Is it a problem that im running CUDA 10.2?

**Comment by rarzumanyan** [comment] 2019-12-28 15:57
CUDA 10.2 shouldn’t be the issue.

The error message you’re receiving means VPF can’t create ffmpeg format context. Is the error specific to rtsp input? I mean, are you able to decode just local file with VPF?

**Comment by roflcoopter** [comment] 2019-12-28 22:50
I seem to get the same error regardless of input actually

**Comment by rarzumanyan** [comment] 2019-12-29 06:19
Most probably this is caused by ffmpeg version mismatch.

VPF uses cmake find_library which is checking default path first and user-provided location second. You can see actual paths to ffmpeg libraries used for compilation in cmake logs. 

Please make sure VPF loads same libs both times.

**Comment by roflcoopter** [comment] 2019-12-29 18:58
You were very much correct! Thank you!
I changed my CMake command to the following:
```
RUN     cd / && \
        git clone https://github.com/NVIDIA/VideoProcessingFramework.git && \
        cd VideoProcessingFramework && \
        mkdir build && \
        cd build && \
        cmake \
            -DFFMPEG_DIR:PATH="/usr/local/ffmpeg" \
            -DVIDEO_CODEC_SDK_DIR:PATH="/usr/local/lib/Video_Codec_SDK_9.1.23" \
            -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
            -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/vpf"\
            -DAVCODEC_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            -DAVFORMAT_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            -DAVUTIL_INCLUDE_DIR:PATH="/usr/local/ffmpeg/include" \
            -DSWRESAMPLE_LIBRARY="/usr/local/ffmpeg/lib/libswresample.so" \
            -DAVFORMAT_LIBRARY="/usr/local/ffmpeg/lib/libavformat.so" \
            -DAVCODEC_LIBRARY="/usr/local/ffmpeg/lib/libavcodec.so" \
            -DAVUTIL_LIBRARY="/usr/local/ffmpeg/lib/libavutil.so" \
            .. &&\
        make -j$(nproc) && \
        make install && \
```
and now it works for an RTSP stream.

FFMPEG is printing a lot of information about lost packets and such. Would be nice if we could pass in special arguments just like we can for the encoder, to set a less verbose log level etc

**Comment by rarzumanyan** [comment] 2019-12-31 09:29
Hi,
Glad that you was able to fix that.
If you don't mind, I'll close the issues and add this information to wiki page.

**Closed by rarzumanyan** 2019-12-31 09:29 UTC

**Comment by pycoco** [comment] 2020-01-04 18:34
@roflcoopter @rarzumanyan i follow the wiki install ffmpeg.but when i install VideoProcessingFramework,use make. error happend.(libavutil.a(error.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC) what can i do ?

**Comment by dexception** [comment] 2020-03-17 14:36
@pycoco It is a verion issue.

**Comment by leviethung2103** [comment] 2020-07-17 17:56
@roflcoopter Have you succesfully build the Docker image for Decode the RTSP stream? Could you please share with me the Dockefile. Thank you so much

**Comment by roflcoopter** [comment] 2020-07-17 21:26
@leviethung2103 
Yes i was succesfull, however i havent really used it since.
I am away over the weekend, i can share with you what i have when i get back home

**Comment by hunglv213** [comment] 2020-07-19 16:34
@roflcoopter, 
Thank you so much. I am looking forward to receive the good news.

**Comment by zachary-dh** [comment] 2020-09-29 16:35
@roflcoopter @leviethung2103 Would you mind sharing the docker file? I have not had any success in trying to get the docker to run properly.

**Comment by thinkinds** [comment] 2021-03-05 01:59
> Hi!
> 
> The stream is H264.
> I am running FFMPEG in a docker container since earlier, and i can succesfully decode the stream using this command:
> 
> ```
> ffmpeg -hwaccel cuvid -c:v h264_cuvid -vsync 0 -rtsp_transport tcp -i rtsp://user:pass@host:554/Streaming/Channels/101/ -vcodec h264_nvenc output.mp4
> ```
> 
> To build VPF inside my container i manually downloaded the Video Codec SDK and added the follwing to my Dockerfile
> 
> ```
> ADD /docker/docker-gpu/Video_Codec_SDK_9.1.23.zip /
> RUN apt-get update &&  apt-get install -y --no-install-recommends unzip cmake git && \
>     unzip -q Video_Codec_SDK_9.1.23.zip -d /usr/local/lib/ && \
>     rm Video_Codec_SDK_9.1.23.zip && \
>     cd / && \
>         git clone https://github.com/NVIDIA/VideoProcessingFramework.git && \
>         cd VideoProcessingFramework && \
>         mkdir build && \
>         cd build && \
>         cmake \
>             -DFFMPEG_DIR:PATH="/usr/local/ffmpeg/bin" \
>             -DVIDEO_CODEC_SDK_DIR:PATH="/usr/local/lib/Video_Codec_SDK_9.1.23" \
>             -DGENERATE_PYTHON_BINDINGS:BOOL="1" \
>             -DCMAKE_INSTALL_PREFIX:PATH="/usr/local/vpf"\ 
>             .. &&\
>         make -j$(nproc) && \
>         make install && \
>     apt-get purge --autoremove -y unzip curl git
> ```
> 
> Is this the correct way of building on Ubuntu?

@roflcoopter Could you please share the dockerfile with me? Thx a lot.

**Comment by roflcoopter** [comment] 2021-03-24 09:15
I am not using VPF anymore, the latest Dockerfile i have is the one pasted in the replies above
