### ISSUE TITLE
Pytorch runs so slow while using "Export torch tensor"

### ISSUE THREAD

**Issue by niaoyu** [NVIDIA/VideoProcessingFramework#35] opened 2020-05-02 16:41 UTC
When  I try to export video frame to Pytorch tensor followed by the new master branch code, everything is fine. 

However, the post processing pytorch model would run quite slow about 6s/pic comparing with 0.1s/pic with cv2.VideoCapture.

Does the gpu decoding to torch gpu tensor cost too much resource? But it does not make sense

**Comment by rarzumanyan** [comment] 2020-05-03 16:20
Hi @niaoyu,

>However, the post processing pytorch model would run quite slow about 6s/pic

Is it just decode + export or it also includes some ML? It's really difficult to judge by the short description. Can you upload a brief code snippet? Just as a reference, I was able to run single shot detector NN for objects classification on 1080p video frame with 30 FPS, so VPF itself shouldn't be very slow.

>Does the gpu decoding to torch gpu tensor cost too much resource?

Video frame export is just cudaMalloc + cudaMemcpy. Moreover, allocated memory objects are cached, so consequent cudaMalloc calls are often omitted.

**Comment by niaoyu** [comment] 2020-05-04 04:14
> Hi @niaoyu,
> 
> > However, the post processing pytorch model would run quite slow about 6s/pic
> 
> Is it just decode + export or it also includes some ML? It's really difficult to judge by the short description. Can you upload a brief code snippet? Just as a reference, I was able to run single shot detector NN for objects classification on 1080p video frame with 30 FPS, so VPF itself shouldn't be very slow.
> 
> > Does the gpu decoding to torch gpu tensor cost too much resource?
> 
> Video frame export is just cudaMalloc + cudaMemcpy. Moreover, allocated memory objects are cached, so consequent cudaMalloc calls are often omitted.

**Comment by rarzumanyan** [comment] 2020-05-04 10:31
Hi @niaoyu,

I generally follow the first approach which is to do ML in the same thread as decode + export. I've tried to use thread-safe FIFO to pass exported frames between multiple threads which didn't succeed. Description below is to my best knowledge, I'm not the Python expert:

- If multiple threads are used, decoder has to pass either video frames or cuda tensors to another thread. AFAIK Python uses serialization method for that which is called 'pickling' which basically describes how to save all the information needed to re-create the object from copiable data. So pickle is essentially a deep copy which is not desirable from my point of view because one Full HD video frame converted to 32-bit float RGB is almost 25 MB so memcpy may impose quite a performance penalty. Single-thread approach saves a lot on cuMalloc + cuMemcpy.

- VPF insides are built around the idea that all basic classes own a small pool of video frames which are allocated at the construction time. Every time you call a method like `DecodeSingleSurface()` it returns reference to underlying memory which will be re-used upon next call. So adding the pickle support for video frame is tricky because it breaks the allocate-once-reference-multiple-times approach. I've also found that CUDA tensors don't support piclke out of the box (maybe for similar reasons).

I'll be honest to you and say that I'm running out of depth here. Exporting video frame to Pytorch tensor as cuMalloc + cuMemcpy was the simplest and most reliable solution I've found but it doesn't go well with passing objects by reference which is against Python approach. If you know a workaround for this issue I'll be super happy to accept it.

**Comment by niaoyu** [comment] 2020-05-05 15:50
@rarzumanyan 
Hi, I just simply my code which 
1)detect once per five frames just in the same thread 
2) export the frame and detections to thread queue,
3) do some post processing just from the thread queue
that's just OK.

But I just have one more question. 
While testing the SampleDecodeMultiThread.py in the master branch, after 2 mins, the error would be shown as "Decode Error occurred for picture 8161No more video frames" in outputs.
The command is just like:
```python
python SampleDecodeMultiThread.py 0 rtmp:111  test1.mp4 0 rtsp:2222 test2.mp4
```

But for just one rtmp url, it will be OK. 
```python
    th1.start()
    # th2.start()
 
    th1.join()
    # th2.join()
```

Are there still some multithread decoding issues in master branch?

**Comment by rarzumanyan** [comment] 2020-05-05 17:16
Hi @niaoyu 

I didn’t face such issues in the testing environment. Though local files are used, not the rtmp stream. Actually, the number of decoded frames is checked to make sure decoder doesn’t miss frames.

Is the problem specific for the input rtmp stream or it also reproduces on other rtsp stream? Does it happens on the same frame number every time or is there run to run difference? Do you access streams over the actual network or is it localhost loop?

**Comment by niaoyu** [comment] 2020-05-06 10:56
```bash
Is the problem specific for the input rtmp stream or it also reproduces on other rtsp stream?
```
The error happens just in the case that "2 rtsp streams while export torch gpu tensors."
I figured out use the SampleDecodeMultiThread.py to just numpy array would be fine.

```bash
Does it happens on the same frame number every time or is there run to run difference? 
```
Just difference

```bash
Do you access streams over the actual network or is it localhost loop?
```
Just two real rtsp streams not local video file.


So the error should be related with multi streams exporting to gpu tensor.
And If the error just show the case "miss frames", It would not be an issue if in a read time video pipeline. Just ignore it would be OK?

**Comment by rarzumanyan** [comment] 2020-05-06 11:17
Hi @niaoyu 

I'm not sure if error is caused by network connectivity of the VPF itself especially if there's run to run difference.

>use the SampleDecodeMultiThread.py to just numpy array would be fine

`DecodeSingleFrame` is actually `DecodeSingleSurface` + `DownloadSingleSurface` combined within single method so there's no difference between them from decoding point of view. 

If you can ignore decode errors which indeed may happen in case of real rtsp streams I think it's fine to do so.

**Comment by mchl0203** [comment] 2020-05-06 11:27
Hi friend @rarzumanyan:
I encountered the same problem as @niaoyu 's, I use 1 GPU to process 4 real-time camera rtsp video streams. After running the program for a period of time(each time is different, about 1 to 2 minutes), the following error will be reported (This problem will cause mosaic patterns to appear in some areas of the decoded picture). Google got a answer: set ffmpeg `rtsp_transport` as `tcp`, how do I set this option in code to try this method. But there may also be network transmission problems, or what other reasons might cause this problem.
Trouble you again ~
```
[rtsp @ 0x490e080] RTP: missed 89 packets
[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed 290 packets
[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed 106 packets
Decode Error occurred for picture 91[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed 297 packets
Decode Error occurred for picture 92Decode Error occurred for picture 93Decode Error occurred for picture 94[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed 94 packets
Decode Error occurred for picture 97[rtsp @ 0x5fc3f00] CSeq 8 expected, 7 received.
[rtsp @ 0x5fc3f00] max delay reached. need to consume packet
[rtsp @ 0x5fc3f00] RTP: missed 7333 packets
[rtsp @ 0x5fc3f00] RTP: PT=60: bad cseq 3e04 expected=215f
[rtsp @ 0x5fc3f00] max delay reached. need to consume packet
[rtsp @ 0x5fc3f00] RTP: missed 7601 packets
[rtsp @ 0x5fc3f00] RTP: PT=60: bad cseq 3f10 expected=215f
[rtsp @ 0x5fc3f00] max delay reached. need to consume packet
[rtsp @ 0x5fc3f00] RTP: missed 7602 packets
[rtsp @ 0x5fc3f00] max delay reached. need to consume packet
[rtsp @ 0x5fc3f00] RTP: missed 129 packets
[rtsp @ 0x5fc3f00] max delay reached. need to consume packet
[rtsp @ 0x5fc3f00] RTP: missed 266 packets
Decode Error occurred for picture 99[rtsp @ 0x490e080] CSeq 8 expected, 7 received.
[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed -55389 packets
[rtsp @ 0x490e080] RTP: PT=60: bad cseq 05b5 expected=de12
[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed -55388 packets
Decode Error occurred for picture 100[rtsp @ 0x490e080] max delay reached. need to consume packet
[rtsp @ 0x490e080] RTP: missed 277 packets
[rtsp @ 0x5ad6200] CSeq 8 expected, 7 received.
[rtsp @ 0x5ad6200] max delay reached. need to consume packet
[rtsp @ 0x5ad6200] RTP: missed 8172 packets
[rtsp @ 0x5ad6200] RTP: PT=60: bad cseq 6dfe expected=4e12
[rtsp @ 0x5ad6200] max delay reached. need to consume packet
[rtsp @ 0x5ad6200] RTP: missed 8173 packets
[rtsp @ 0x5ad6200] max delay reached. need to consume packet
[rtsp @ 0x5ad6200] RTP: missed 228 packets
Decode Error occurred for picture 102[rtsp @ 0x5ad6200] max delay reached. need to consume packet
[rtsp @ 0x5ad6200] RTP: missed 171 packets
Decode Error occurred for picture 103[rtsp @ 0x5ad6200] max delay reached. need to consume packet
[rtsp @ 0x5ad6200] RTP: missed 202 packets
Decode Error occurred for picture 105
```

**Comment by rarzumanyan** [comment] 2020-05-06 11:32
hi @mchl0203 

>how do I set this option in code

I guess it shall be passed as AVDictionary value. I'll create a branch for this and will try to add ffmpeg dictionary support, it shouldn't be too difficult.

**Comment by niaoyu** [comment] 2020-05-06 11:40
```bash
DecodeSingleFrame is actually DecodeSingleSurface + DownloadSingleSurface combined within single method so there's no difference between them from decoding point of view
```

Yes, but i want to use makefromDevicePtrUint8 to get a torch gpu tensor not a numpy array. So maybe DecodeSingleFrame is not the choice.(The error would be show only the torch version)

```
If you can ignore decode errors which indeed may happen in case of real rtsp streams I think it's fine to do so.
```
I could do nothing when the error show, there is no decoding output so what should i do, if I want to ignore the error?

**Comment by niaoyu** [comment] 2020-05-06 11:41
> Hi friend @rarzumanyan:
> I encountered the same problem as @niaoyu 's, I use 1 GPU to process 4 real-time camera rtsp video streams. After running the program for a period of time(each time is different, about 1 to 2 minutes), the following error will be reported (This problem will cause mosaic patterns to appear in some areas of the decoded picture). Google got a answer: set ffmpeg `rtsp_transport` as `tcp`, how do I set this option in code to try this method. But there may also be network transmission problems, or what other reasons might cause this problem.
> Trouble you again ~
> 
> ```
> [rtsp @ 0x490e080] RTP: missed 89 packets
> [rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed 290 packets
> [rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed 106 packets
> Decode Error occurred for picture 91[rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed 297 packets
> Decode Error occurred for picture 92Decode Error occurred for picture 93Decode Error occurred for picture 94[rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed 94 packets
> Decode Error occurred for picture 97[rtsp @ 0x5fc3f00] CSeq 8 expected, 7 received.
> [rtsp @ 0x5fc3f00] max delay reached. need to consume packet
> [rtsp @ 0x5fc3f00] RTP: missed 7333 packets
> [rtsp @ 0x5fc3f00] RTP: PT=60: bad cseq 3e04 expected=215f
> [rtsp @ 0x5fc3f00] max delay reached. need to consume packet
> [rtsp @ 0x5fc3f00] RTP: missed 7601 packets
> [rtsp @ 0x5fc3f00] RTP: PT=60: bad cseq 3f10 expected=215f
> [rtsp @ 0x5fc3f00] max delay reached. need to consume packet
> [rtsp @ 0x5fc3f00] RTP: missed 7602 packets
> [rtsp @ 0x5fc3f00] max delay reached. need to consume packet
> [rtsp @ 0x5fc3f00] RTP: missed 129 packets
> [rtsp @ 0x5fc3f00] max delay reached. need to consume packet
> [rtsp @ 0x5fc3f00] RTP: missed 266 packets
> Decode Error occurred for picture 99[rtsp @ 0x490e080] CSeq 8 expected, 7 received.
> [rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed -55389 packets
> [rtsp @ 0x490e080] RTP: PT=60: bad cseq 05b5 expected=de12
> [rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed -55388 packets
> Decode Error occurred for picture 100[rtsp @ 0x490e080] max delay reached. need to consume packet
> [rtsp @ 0x490e080] RTP: missed 277 packets
> [rtsp @ 0x5ad6200] CSeq 8 expected, 7 received.
> [rtsp @ 0x5ad6200] max delay reached. need to consume packet
> [rtsp @ 0x5ad6200] RTP: missed 8172 packets
> [rtsp @ 0x5ad6200] RTP: PT=60: bad cseq 6dfe expected=4e12
> [rtsp @ 0x5ad6200] max delay reached. need to consume packet
> [rtsp @ 0x5ad6200] RTP: missed 8173 packets
> [rtsp @ 0x5ad6200] max delay reached. need to consume packet
> [rtsp @ 0x5ad6200] RTP: missed 228 packets
> Decode Error occurred for picture 102[rtsp @ 0x5ad6200] max delay reached. need to consume packet
> [rtsp @ 0x5ad6200] RTP: missed 171 packets
> Decode Error occurred for picture 103[rtsp @ 0x5ad6200] max delay reached. need to consume packet
> [rtsp @ 0x5ad6200] RTP: missed 202 packets
> Decode Error occurred for picture 105
> ```

You could do some change like this, which I am using now.


```c++

AVFormatContext *FFmpegDemuxer::CreateFormatContext(const char *szFilePath) {
  avformat_network_init();

  AVDictionary *avdic=NULL;
  char option_key[]="rtsp_transport";
  char option_value[]="tcp";
  av_dict_set(&avdic,option_key,option_value,0);
  char option_key2[]="max_delay";
  char option_value2[]="5000000";
  av_dict_set(&avdic, option_key2, option_value2, 0);


  AVFormatContext *ctx = nullptr;
//  auto err = avformat_open_input(&ctx, szFilePath, nullptr, nullptr);
  auto err = avformat_open_input(&ctx, szFilePath, nullptr, &avdic);
  if (err < 0) {
    std::cerr << "Can't open " << szFilePath << ": " << AvErrorToString(err)
              << "\n";
    return nullptr;
  }

  return ctx;
}
```

**Comment by rarzumanyan** [comment] 2020-05-06 12:35
Please check branch `issue_35`
Now you should be able to pass ffmpeg options to PyNvDecoder:
```python
nvDec = nvc.PyNvDecoder(encFilePath, gpuID, {'rtsp_transport' : 'tcp', 'max_delay' : '5000000'})
```

Empty dictionary is also valid:
```python
nvDec = nvc.PyNvDecoder(encFilePath, gpuID, {})
```

Please let me know if it fixes the problem. If it does, I'll merge to master.

**Comment by niaoyu** [comment] 2020-05-06 12:59
> Hi, @rarzumanyan
> 
> ```shell
> DecodeSingleFrame is actually DecodeSingleSurface + DownloadSingleSurface combined within single method so there's no difference between them from decoding point of view
> ```
> 
> Yes, but i want to use makefromDevicePtrUint8 to get a torch gpu tensor not a numpy array. So maybe DecodeSingleFrame is not the choice.(The error would be show only the torch version)
> 
> ```
> If you can ignore decode errors which indeed may happen in case of real rtsp streams I think it's fine to do so.
> ```
> 
> I could do nothing when the error show, there is no more decoding output so what should i do, if I want to ignore the error?

@rarzumanyan 
Hi, arzumanyan. 
Should I need to use the numpy version rather than the torch version to avoid the issue?

**Comment by rarzumanyan** [comment] 2020-05-06 13:19
hi @niaoyu 

I think you may try to pass ffmpeg options first. According to @mchl0203 it shall solve the issue.
If it does, just stick to existing `DecodeSingleSurface` approach.

Once again, there's no difference between `DecodeSingleSurface` and `DecodeSingleFrame` in how the bitstream is demuxed and passed to decoder. `DecodeSingleFrame` does exactly the same thing, it just copies surface to numpy array in the end.

**Comment by niaoyu** [comment] 2020-05-06 13:41
Thanks, @rarzumanyan 
```bash
pass ffmpeg options first.
``` 
actually I have already pass the option by myself. But i will try the new version.

```bash
there's no difference between DecodeSingleSurface and DecodeSingleFrame
```
Er...I am always using DecodeSingleSurface and use makefromDevicePtrUint8 get a torch tensor, not using DecodeSingleFrame.

**Comment by rarzumanyan** [comment] 2020-05-06 13:47
@niaoyu 
Okay, so I'm probably confusing yours answers with that from @mchl0203 

So if you pass `{'rtsp_transport' : 'tcp', 'max_delay' : '5000000'}` - does that solve the issue? 
Can you decode rtsp videos from 2 threads simultaneously with export to Pytorch tensors?

**Comment by mchl0203** [comment] 2020-05-06 14:38
Hi @rarzumanyan :
Use `{'rtsp_transport' : 'tcp', 'max_delay' : '5000000'}` can solve the following error:
```
[rtsp @ 0x490e080] RTP: missed 290 packets
[rtsp @ 0x490e080] max delay reached. need to consume packet
```
But there are still problems he said @niaoyu , and I tried to decode rtsp into numpy array and tensor, the following error appears.
```
[rtsp @ 0x55775ee7a300] CSeq 8 expected, 6 received.
[rtsp @ 0x55775ee7a300] RTP: PT=60: bad cseq ef80 expected=cf9c
[rtsp @ 0x5600f3a46b80] CSeq 8 expected, 6 received.
[rtsp @ 0x5600f3a46b80] RTP: PT=60: bad cseq 4142 expected=218c
Decode Error occurred for picture 115
[rtsp @ 0x5600f3a46b80] CSeq 9 expected, 7 received.
[rtsp @ 0x55775ee7a300] CSeq 9 expected, 7 received.
Decode Error occurred for picture 137
[rtsp @ 0x5600f3a46b80] RTP: PT=60: bad cseq 5bb5 expected=4f0a
Decode Error occurred for picture 154
Decode Error occurred for picture 156
Decode Error occurred for picture 156
[rtsp @ 0x55775ee7a300] CSeq 10 expected, 8 received.
```

**Comment by rarzumanyan** [comment] 2020-05-06 15:14
Thanks for update @mchl0203

I believe this is FFmpeg issue, not the VPF one. Here is what I've found after googling the error messages: 

- https://github.com/Motion-Project/motion/issues/950#issue-450314990

- https://trac.ffmpeg.org/ticket/258

VPF basically feeds NV hardware with Annex.B elementary video bitstream which is taken from ffmpeg demuxer. If Annex.B stream is broken due to network losses or possible bugs in FFmpeg library, unfortunately there's nothing I can do with that. 

However if you can decode the RTSP stream with ffmpeg application it means that some AVDictionary settings are missed and you can pass them to VPF using the latest patch from the `issue_35` branch.

**Comment by rarzumanyan** [comment] 2020-05-06 15:27
As original issue was solved, I'm closing this. 
Please open new issue in case you run into further problems.

**Closed by rarzumanyan** 2020-05-06 15:27 UTC
