### ISSUE TITLE
Multiprocessing support requirement

### ISSUE THREAD

**Issue by LuletterSoul** [NVIDIA/VideoProcessingFramework#62] opened 2020-06-09 13:09 UTC
Hello, thanks for your contributions and kindness! 
 
I have to run  object detection algorithm for multiple RTSP streams on a 12-cores CPU now.
I consider initialize VBF components for each RTSP stream on a subprocess and share GPU resources between subprocess using multiprocessing communication. 

```
def start_test():
    workers = list()

    for i in range(4):
        th = StreamDecoder(gpus[i % 4], inputs[i % 2], i) 
        workers.append(th)

    with Pool(10) as p:
        for i in range(len(workers)):
            # StreamDecoder encapsulates VBF components, so when the decoder runs on a 
                subprocess, 
            # all components belong the decoder must be pickled from main process
            res = p.apply_async(workers[i].run)
            res.get()
        p.close()
        p.join()
```

But, It seems to be that VBF cannot run in a subprocess due to related thread components usage.
Here is what error I encountered:

```
Traceback (most recent call last):
  File "/home/jt1/VideoProcessingFramework/install/bin/testMutilRtsp2.py", line 134, in <module>
    start_test()
  File "/home/jt1/VideoProcessingFramework/install/bin/testMutilRtsp2.py", line 121, in start_test
    res.get()
  File "/home/jt1/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/jt1/miniconda3/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/jt1/miniconda3/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/jt1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle PyNvCodec.PyNvDecoder objects

Process finished with exit code 1

```

Is it possible that refactor PyNvCodec and make it free from pickling?

**Comment by rarzumanyan** [comment] 2020-06-09 13:53
Hi @LuletterSoul 

>Is it possible that refactor PyNvCodec and make it free from pickling?

Actually VPF doesn't support pickling because pickle is a deep-copy approach used to serialize Python objects. VPF entities (such as PyNvDecoder class) aren't copy-able.

The error you see is caused by fact that Python needs VPF classes to be copy-able to support data exchange between threads & processes (you add pool of decoders to list which uses deep copy under the hood).

I recommend you to take a look at `SampleDecodeMultiThread.py` which illustrates how to create multiple Decoder classes each of which runs in separate thread. It will also work with multiprocess Python module.

**Comment by LuletterSoul** [comment] 2020-06-09 14:31
@rarzumanyan Always quick response you give! Thanks. I understand  multiple Decoder classes could run in separate thread.But It cannot boost mutil-cores power fully when Python GIL exists.

That is the reason why I using multi-processing to breakthrough GIL limitation.
Why aren't VPF entities copy-able?

**Comment by rarzumanyan** [comment] 2020-06-09 16:00
>Why aren't VPF entities copy-able?

Due to performance reasons. 
E. g. decoder allocates a pool of memory objects which are used to store video frames.
Every time you call `DecodeSingleSurface` it returns pointer to one of the frames from pool.
Otherwise it will have to allocate CUDA memory and copy which is slow.

>I understand multiple Decoder classes could run in separate thread.But It cannot boost mutil-cores power fully when Python GIL exists.

I recommend you to start performance profiling from simple `nvidia-smi -dmon` console command. If you run multiple video decoder instances, chances are you will be limited by Nvdec performance and not only by CPU.

**Comment by rarzumanyan** [comment] 2020-06-10 06:17
I’m closing this because VPF can’t support pickling for all of it’s classes by design.

E. g. PyNvDecoder class has Video Codec SDK API structures within that don’t have functions for copying them (such as parser, decoder, etc).

**Closed by rarzumanyan** 2020-06-10 06:17 UTC

**Comment by LuletterSoul** [comment] 2020-06-10 06:50
> I’m closing this because VPF can’t support pickling for all of it’s classes by design.
> 
> E. g. PyNvDecoder class has Video Codec SDK API structures within that don’t have functions for copying them (such as parser, decoder, etc).

Thanks very much. I think I got a better solution than putting VBF entities inside a process pool now.Actually VBF could be initialized in a Python module.And python module will be imported by each process independently.So It's unnecessary to trigger serialization by process pool.

**Comment by niaoyu** [comment] 2020-09-22 03:05
> > I’m closing this because VPF can’t support pickling for all of it’s classes by design.
> > E. g. PyNvDecoder class has Video Codec SDK API structures within that don’t have functions for copying them (such as parser, decoder, etc).
> 
> Thanks very much. I understand good program design of VBF.I think I got a better solution than putting VBF entities inside a process pool now.Actually VBF could be initialized in a Python module.And python module will be imported by each process independently.So It's unnecessary to trigger serialization by process pool.

Hi, could you just show some examples about applying VPF as python module with multi-process?
