### ISSUE TITLE
Decode Error occurred for picture 4766？

### ISSUE THREAD

**Issue by sbbug** [NVIDIA/VideoProcessingFramework#47] opened 2020-05-17 10:11 UTC
Hello!
When I parsed rtsp stream,I encountered the error：
**Decode Error occurred for picture 4766。**

My config is :
 **self.nvDec = nvc.PyNvDecoder(encFile, gpuID,
                                     {'acodec': 'copy', 'vcodec': 'copy', 'rtsp_transport': 'tcp',
                                      'max_delay': '5000000', 'bufsize': '30000k'})**
Can you help me ?
What causes this problem？

**Comment by rarzumanyan** [comment] 2020-05-17 10:21
Hi @sbbug,

This is duplicate of the https://github.com/NVIDIA/VideoProcessingFramework/issues/39#issue-613736718, please take a look at it first.

```python
My config is :
self.nvDec = nvc.PyNvDecoder(encFile, gpuID, 
{'acodec': 'copy', 
'vcodec': 'copy', 
'rtsp_transport': 'tcp', 
'max_delay': '5000000', 
'bufsize': '30000k'})
```

You don't need to set ` 'acodec': 'copy', 'vcodec': 'copy' ` options. They are needed for transcoding, when you want transcoded video to have audio and video codecs same to that in input file.

**Comment by sbbug** [comment] 2020-05-17 11:35
@rarzumanyan 
After reading [https://github.com/NVIDIA/VideoProcessingFramework/issues/39#issue-613736718](url),I modify my code as:

 ```
while True:

                # time.sleep(2)
                start = time.time()
                rawSurface = self.nvDec.DecodeSingleSurface()
                # print(rawSurface)
                if (rawSurface.Empty()):
                    print('No more video frames')
                    **self.nvDec = nvc.PyNvDecoder(self.encFile, self.gpuID,
                                                 { 'rtsp_transport': 'tcp',
                                                   'max_delay': '5000000', 'bufsize': '30000k'})
                    continue**

                cvtSurface = self.nvCvt.Execute(rawSurface)
                if (cvtSurface.Empty()):
                    print('Failed to do color conversion')
                    break
```
but I encontered the problem:
Decode Error occurred for picture 4788

why?
It does not seem to work.

**Comment by sbbug** [comment] 2020-05-17 11:38
What do you think is the cause，code bug or Bandwidth issue？

**Comment by rarzumanyan** [comment] 2020-05-17 17:56
@sbbug,

If you can download the RTSP stream with ffmpeg application or any other, you can do that and check VPF against the local copy. In  case the issue reproduces on local stream, that's definitely bug. Otherwise it may be bandwidth issue or some ffmpeg parameters missed.

I'll also check VPF on some of public RTSP streams, as this is not the first time people have issue with RTSP after some decoding time.

**Comment by rarzumanyan** [comment] 2020-05-18 06:58
@sbbug 
I've launched SampleDecode overnight using one of the public RTSP streams:

```
SampleDecode.py 0 rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream output.nv12
```

It has been running for 4:52:12 without any issues, then it disconnected because of decode error:
```
Decode Error occurred for picture 885520
Decode Error occurred for picture 1033736
```
I didn't reopen the URL and / or recreated the decoder instance to increase robustness, it was just vanilla decoding sample with 2 exceptions:

- decoder was created with parameters same to yours: `{ 'rtsp_transport': 'tcp', 'max_delay': '5000000', 'bufsize': '30000k'}`

- I was saving not every single frame but once a second to reduce output file size.

So IMHO it looks pretty reliable.

**Comment by LuletterSoul** [comment] 2020-06-10 09:51
@rarzumanyan Hey, I faced the same problem here.


When the 4K RTSP stream is plugged by VBF, the program can decode smoothly for a period of time,then the error will appear as below:

`
Decode Error occurred for picture 7692
`

The real-time display debug shows that the video stream has obvious frame dropping but all frames look complete.I think this error caused by `Decode Error`. I also google some useful log information in the Nvidia HW source code:
```
    if (result == CUDA_SUCCESS && (DecodeStatus.decodeStatus == cuvidDecodeStatus_Error || DecodeStatus.decodeStatus == cuvidDecodeStatus_Error_Concealed))
    {
        printf("Decode Error occurred for picture %d\n", m_nPicNumInDecodeOrder[pDispInfo->picture_index]);
    }
```

It only proves that CUDA return a decode error status but I don't know why.BTW, Using 'rtsp_transport': 'tcp' option solves packet loss problem perfectly in my system.If no packet loss there, why decode error happed? I have read issue #39 carefully.


I also play these RTSP streams in VLC player, it plays smoothly and no frame is dropped. 
So frame dropping showed by VBF really confused me.I almost there to finish HW decoding but trapped by this error. I  need you help and your professional advice sincerely!

**Comment by rarzumanyan** [comment] 2020-06-10 10:11
@LuletterSoul 
Did you try to re-create PyNvDecoder class instance?

**Comment by LuletterSoul** [comment] 2020-06-10 10:15
@rarzumanyan No, because this error don't bring any exception and just let program keep going, rawsurface is not empty and download single surface successfully for each iteration.

**Comment by rarzumanyan** [comment] 2020-06-10 10:32
@LuletterSoul 
You're right, it indeed only prints the message in log.
I've added the patch which makes decoder throw exception when it fails to decode. It's in `issue_47` branch. Please take a look at it.

**Comment by LuletterSoul** [comment] 2020-06-10 11:54
@rarzumanyan Great! I estimated the time when the decoding error occurred. The time interval is short and it will throw decode error exception frequently.If a decoding error has occurred, we re-create PyNvDecoder instantly, will it cause frame discontinuity, or cost much CPU resources ?

Is there exist the other way to fix decode error gracefully?

**Comment by rarzumanyan** [comment] 2020-06-11 11:39
@LuletterSoul 

I've pushed the patch to `issue_47` branch which automatically resets only HW decoder in case of exception thrown during decoding process. 

It doesn't affect FFmpeg demuxer under the hood so the RTSP connection shouldn't be re-established in case of decoding error. This should decrease reset time and make it less invasive.

**Comment by rarzumanyan** [comment] 2020-06-16 06:44
@sbbug, @LuletterSoul 
Pushed a patch to `issue_47` branch which adds `HwResetException` custom Python exception.
It happens when decoder faces an error and resets:
https://github.com/NVIDIA/VideoProcessingFramework/blob/d2a39c7de230ae075336e5a5c2022fb3567b167e/SampleDecodeMultiThread.py#L38-L51

I've left the `SampleDecodeMultiThread.py` running overnight, HW decoder was reset multiple times without breaking the RTSP connection.
Decoder reset time on my machine is around 8 milliseconds which is IMO fine.
Closing this issue as fixed, please reopen in case you still face same problem.

**Closed by rarzumanyan** 2020-06-16 06:44 UTC

**Comment by LuletterSoul** [comment] 2020-06-16 14:35
@rarzumanyan 
Thanks, error was found when building VPF:
```
/home/ndww/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:171:30: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
   atomic<int> decode_error = 0;
                              ^
In file included from /home/ndww/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:15:0:
/usr/include/c++/7/atomic:668:7: note: declared here
       atomic(const atomic&) = delete;
       ^~~~~~
/usr/include/c++/7/atomic:672:17: note:   after user-defined conversion: constexpr std::atomic<int>::atomic(std::atomic<int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
                 ^~~~~~
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:158: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/NvDecoder.cpp.o' failed
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/NvDecoder.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/all' failed
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

What's decoder_error using for?

**Comment by rarzumanyan** [comment] 2020-06-16 15:06
Hi @LuletterSoul 

```cpp
/home/ndww/VideoProcessingFramework/PyNvCodec/TC/src/NvDecoder.cpp:171:30: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
   atomic<int> decode_error = 0;
```
It's used to signal decode error from decode callback.
Strange that it doesn't compile on your machine.
I guess you can just change this line to
```cpp
atomic<int> decode_error;
```

**Comment by LuletterSoul** [comment] 2020-06-16 15:16
@rarzumanyan 
It works! But the other error thrown:

```
[100%] Linking CXX shared library libTC.so
/usr/bin/ld: /usr/local/lib/libavcodec.a(cavsdsp.o): relocation R_X86_64_PC32 against symbol `ff_pw_96' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:309: recipe for target 'PyNvCodec/TC/libTC.so' failed
make[2]: *** [PyNvCodec/TC/libTC.so] Error 1
CMakeFiles/Makefile2:117: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/all' failed
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by rarzumanyan** [comment] 2020-06-16 15:21
@LuletterSoul 

You're linking VPF against static FFmpeg links.
Dynamic linking (against *.so libs) is required. Probably you need to update `FFMPEG_DIR` in your Cmake file.

**Comment by sbbug** [comment] 2020-06-18 05:45
@rarzumanyan 
There will be no screen when parsing the video, but there will be a lag when playing the video.

**Comment by LuletterSoul** [comment] 2020-06-18 06:46
@rarzumanyan 

Hi, I must thank you again for generous help. But, there is obvious frame dropping.Thought the decoder is reset, frames are dropped and loss permanently. It's the most terrible that decode error 
occurs frequently.

[Screen Recording 2020-06-18 at 2.35.09 PM 1.mp4.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/4796701/Screen.Recording.2020-06-18.at.2.35.09.PM.1.mp4.zip)

**Comment by rarzumanyan** [comment] 2020-06-18 13:14
@LuletterSoul 

>But, there is obvious frame dropping.Thought the decoder is reset, frames are dropped and loss permanently

To improve this, decoder class re-design is required (demuxer must store compressed frames into separate queue from which decoder shall take them + decoder shall put raw frames into another queue). This will allow to minimize the number of frames dropped. 

However, some effort is required to do this & I'm not sure I take it up right now. 

Can you please set up separate feature request issue which I will address a bit later as I have bandwidth to implement it?

**Comment by LuletterSoul** [comment] 2020-06-18 13:29
@rarzumanyan 
Ok, I will open a new issue for this feature.

**Comment by whatisor** [comment] 2021-06-04 03:23
@rarzumanyan, should we go further to find the root cause?
Reset decoder is a temporary solution which mean we could not find the root cause.
We should not close the issue of framework with this solution?

**Comment by rarzumanyan** [comment] 2021-06-04 08:07
Hi @whatisor 

This issue was closed long time ago.
Please go through latest samples which support decoder reset, external demuxers support and other means which improve stability.
