### ISSUE TITLE
RuntimeError: can't get unknown filter by name

### ISSUE THREAD

**Issue by hongsong-wang** [NVIDIA/VideoProcessingFramework#223] opened 2021-07-08 08:33 UTC
vpf reports bugs while decoding some videos:
  
File "SampleDecodeMultiThread_multi.py", line 171, in <module>
    create_threads(gpu_id, input_file, num_threads)
  File "SampleDecodeMultiThread_multi.py", line 141, in create_threads
    thread = Worker(gpu_id, input_file)
  File "SampleDecodeMultiThread_multi.py", line 62, in __init__
    self.nvDec = nvc.PyNvDecoder(encFile, self.ctx.handle, self.str.handle)

I find the same issue have been raised in:
https://github.com/NVIDIA/VideoProcessingFramework/issues/9

But this problem has not been solved. So I raise this issue again.

**Comment by rarzumanyan** [comment] 2021-07-08 08:42
Hi @hongsong-wang 

What's the input video you're trying to decode?

**Comment by hongsong-wang** [comment] 2021-07-08 11:44
For the video which is generated by FFMEPG, e.g., 
ffmpeg -i input.avi -vf scale="iw/2:ih/2" output.avi

VPF could decode the input.avi, but cannot decode the output.avi

**Comment by rarzumanyan** [comment] 2021-07-08 11:50
Run `ffprobe output.avi` to see what video codec is used.
So far VPF supports h.264, h.265 and vp9.

**Comment by hongsong-wang** [comment] 2021-07-09 07:31
Thanks!
Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D)

**Comment by rarzumanyan** [comment] 2021-07-09 08:35
That, the reason.
Please re-encode it to one of supported formats e. g. like this:
```
ffmpeg -i input.avi -vf scale="iw/2:ih/2" -c:v h264 output.avi
```
Or with VPF.

Closing as duplicate of #9

**Closed by rarzumanyan** 2021-07-09 08:35 UTC
