### ISSUE TITLE
Repeated frames in output video

### ISSUE THREAD

**Issue by yuval-vi** [NVIDIA/VideoProcessingFramework#317] opened 2022-03-30 07:37 UTC
Hi @rarzumanyan,
We are testing the SamplePyTorch.py example (as is) on an AWS g4dn.xlarge machine.

We consistently see that the 3rd and 4th frames appear twice (i.e. 0, 1, 2, 3, 4, 3, 4, 5, 6, ...).
Verified by a frame-numbered video as input, that has a correct order of frames.

Do you maybe know what might cause it? And does it happen on other setups?

Let me know if you want the input/output videos..

Thanks in advance,
Yuval

**Comment by rarzumanyan** [comment] 2022-03-30 07:43
Hi @yuval-vi 

There are 2 things we need to check:

1. Please verify the frame duplication here: https://github.com/NVIDIA/VideoProcessingFramework/blob/83b72de0bcf815a17cbfc57a7cc0d542cf73e04b/SamplePyTorch.py#L81 by saving it to the disk. Need to investigate where the duplication happens: on `PyNvDecoder` side or within Pytorch.
2. Please send me the video (if possible) on which the issue reproduces.

Additionally, you may run tests from https://github.com/NVIDIA/VideoProcessingFramework/blob/master/Tests/test_PyNvDecoder.py. Just make sure you fix the file paths and ground truth video characteristics:
https://github.com/NVIDIA/VideoProcessingFramework/blob/83b72de0bcf815a17cbfc57a7cc0d542cf73e04b/Tests/test_PyNvDecoder.py#L48-L58

**Comment by yuval-vi** [comment] 2022-03-30 10:23
Thanks @rarzumanyan,
Will investigate using the points you sent.
Is there an email address I can send the video to? 

Thanks

**Comment by rarzumanyan** [comment] 2022-03-30 11:17
@yuval-vi 

>Is there an email address I can send the video to?

Please send it to my email (in profile description).

**Comment by rarzumanyan** [comment] 2022-03-30 11:47
@yuval-vi 

I've decoded your video with SampleDecode.py and all the frames are in the right places, no repetitions.

**Comment by yuval-vi** [comment] 2022-03-30 16:35
Thanks @rarzumanyan

**Comment by rarzumanyan** [comment] 2022-03-31 09:11
Hi @yuval-vi 

Please check latest `SamplePyTorch.py`. It looks like CUDA sync was missing.
After adding the sync the frame no longer reproduces on my machine. Please confirm that issue is fixed on your side.

**Comment by yuval-vi** [comment] 2022-04-03 10:30
Hi @rarzumanyan,
We confirm that the fix works for us too.
The new example is also much better and easier to use. 

Thanks for all the great work!

**Comment by yuval-vi** [comment] 2022-04-03 10:32
BTW the ```import cv2``` in the example is unused

**Comment by rarzumanyan** [comment] 2022-04-03 13:41
Closing as fixed.

**Closed by rarzumanyan** 2022-04-03 13:41 UTC
