### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by XZG-0457** [NVIDIA/VideoProcessingFramework#74] opened 2020-07-06 07:04 UTC
/VideoProcessingFramework-master/PyNvCodec/TC/inc/NppCommon.hpp:21:22: error: ‘NppStreamContext’ has not been declared
                      NppStreamContext &nppCtx);
                      ^~~~~~~~~~~~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/inc/NppCommon.hpp:25:37: error: expected ‘)’ before ‘&’ token
   explicit NppLock(NppStreamContext &nppCtx);
                                     ^
/VideoProcessingFramework-master/PyNvCodec/TC/inc/NppCommon.hpp:29:3: error: ‘NppStreamContext’ does not name a type; did you mean ‘VideoContext’?
   NppStreamContext &ctx;
   ^~~~~~~~~~~~~~~~
   VideoContext
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:773:3: error: ‘NppStreamContext’ does not name a type; did you mean ‘AVFormatContext’?
   NppStreamContext nppCtx;
   ^~~~~~~~~~~~~~~~
   AVFormatContext
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp: In constructor ‘VPF::ResizeSurface_Impl::ResizeSurface_Impl(uint32_t, uint32_t, VPF::Pixel_Format, CUcontext, CUstream)’:
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:778:37: error: ‘nppCtx’ was not declared in this scope
     SetupNppContext(cu_ctx, cu_str, nppCtx);
                                     ^~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:778:37: note: suggested alternative: ‘nppZCC’
     SetupNppContext(cu_ctx, cu_str, nppCtx);
                                     ^~~~~~
                                     nppZCC
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp: At global scope:
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:835:3: error: ‘NppStreamContext’ does not name a type; did you mean ‘AVFormatContext’?
   NppStreamContext nppCtx;
   ^~~~~~~~~~~~~~~~
   AVFormatContext
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NppResizeSurfaceRGB_Impl::Execute(VPF::Surface&)’:
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:823:18: error: ‘nppCtx’ was not declared in this scope
     NppLock lock(nppCtx);
                  ^~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:823:18: note: suggested alternative: ‘nppZCC’
     NppLock lock(nppCtx);
                  ^~~~~~
                  nppZCC
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:825:16: error: ‘nppiResize_8u_C3R_Ctx’ was not declared in this scope
     auto ret = nppiResize_8u_C3R_Ctx(pSrc, nSrcStep, oSrcSize, oSrcRectROI,
                ^~~~~~~~~~~~~~~~~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:825:16: note: suggested alternative: ‘nppiResize_8u_C3R’
     auto ret = nppiResize_8u_C3R_Ctx(pSrc, nSrcStep, oSrcSize, oSrcRectROI,
                ^~~~~~~~~~~~~~~~~~~~~
                nppiResize_8u_C3R
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp: In member function ‘virtual VPF::TaskExecStatus VPF::NppResizeSurfaceYUV420_Impl::Execute(VPF::Surface&)’:
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:877:20: error: ‘nppCtx’ was not declared in this scope
       NppLock lock(nppCtx);
                    ^~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:877:20: note: suggested alternative: ‘nppZCC’
       NppLock lock(nppCtx);
                    ^~~~~~
                    nppZCC
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:879:18: error: ‘nppiResize_8u_C1R_Ctx’ was not declared in this scope
       auto ret = nppiResize_8u_C1R_Ctx(pSrc, nSrcStep, oSrcSize, oSrcRectROI,
                  ^~~~~~~~~~~~~~~~~~~~~
/VideoProcessingFramework-master/PyNvCodec/TC/src/Tasks.cpp:879:18: note: suggested alternative: ‘nppiResize_8u_C1R’
       auto ret = nppiResize_8u_C1R_Ctx(pSrc, nSrcStep, oSrcSize, oSrcRectROI,
                  ^~~~~~~~~~~~~~~~~~~~~
                  nppiResize_8u_C1R
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:86: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o' failed
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o] Error 1
CMakeFiles/Makefile2:160: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/all' failed
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by XZG-0457** [comment] 2020-07-06 07:08
Ubuntu 18.04
cuda 10.0
video_SDK 10.0.26 / video_SDK 9.0.21 All used
ffmpeg 4.2.3


Is the version I use doesn't match？Why does "nppstreamcontext" do not name a type; did you mean 'videocontext'

**Comment by rarzumanyan** [comment] 2020-07-06 08:27
Hi @XZG-0457 

This issue is duplicate of https://github.com/NVIDIA/VideoProcessingFramework/issues/54
Please update the Video Codec SDK to latest version according to wiki.

**Closed by rarzumanyan** 2020-07-06 08:27 UTC
