### ISSUE TITLE
An example in C++ for reading (decoding) a video file into a torch tensor

### ISSUE THREAD

**Issue by QuantScientist** [NVIDIA/VideoProcessingFramework#111] opened 2020-09-22 19:25 UTC
Dear Team, 

I am the author of https://github.com/QuantScientist/PngTorch which uses the latest Libtorch version. I am now interested in decoding a video file into frames that are converted to torch::tensor. Is there such a C++ example somewhere? The Wiki has a python example which is irrelevant to me,

Thanks

**Comment by rarzumanyan** [comment] 2020-09-22 19:42
Hi @QuantScientist 

This is a duplicate of #87.
Please take a look at [this comment](https://github.com/NVIDIA/VideoProcessingFramework/issues/88#issuecomment-669188408).
I've added pure C++ build support in separate branch though the feature requester never came back.
Unfortunately I don't have enough time for extensive triage so if you can take this up that would be great.
Closing this one as duplicate, please respond in #87 comments section.

**Closed by rarzumanyan** 2020-09-22 19:42 UTC
