### ISSUE TITLE
Get contiguous gpu memory from surface

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#174] opened 2021-03-18 13:57 UTC
Hi,
Is there any simpler way to get contiguous gpu memory for rgb planar surface?
This implies pitch = width.

**Comment by rarzumanyan** [comment] 2021-03-18 15:21
Hi @vtpl1

Could you elaborate on that? What exactly do you mean?
Planar RGB surface is just a 2D pitched CUDA memory chunk, you can even obtain it's cudeviceptr.
Pitched allocation is used across VPF for sake of performance. This way the image rows are aligned in memory. 
Beside that most NPP and CUDA functions do require a pitch so you won't make code easier by making `pitch = width`.

**Comment by vtpl1** [comment] 2021-03-18 16:45
Hi @rarzumanyan 
Consider the following case:
```
s = nvc.Surface.Make(nvc.PixelFormat.RGB_PLANAR, 416, 416, 0)
logging.info(
    f"Width: {s.Width()} Height: {s.Height()} Pitch: {s.Pitch()} NumPlanes: {s.NumPlanes()} HostSize: {s.HostSize()}"
)
```
output:
`Width: 416 Height: 416 Pitch: 512 NumPlanes: 3 HostSize: 519168`

Now the application which needs gpu memory needs one dimensional array (**contiguous gpu memory** of 519168 bytes of valid data.
But above code `Surface` would give `512*416*3 = 638976` aligned data with intermediate unusable data beyond `416` bytes.

**Comment by rarzumanyan** [comment] 2021-03-18 18:04
Hi @vtpl1 

I get your point.
Yes, pitched allocation indeed wastes some memory.
Although the excessive amount of bytes allocated is usually negligible and doesn't overweight the performance gain.
So I'm basically following the Video Codec SDK programming guide and use 2D pitched allocation.

Did you actually come across the situation when GPU memory is completely occupied due to pitched allocation and lack of vRAM limits your application?

**Comment by vtpl1** [comment] 2021-03-18 18:23
Hi @rarzumanyan ,
It is not about the extra memory but the application like tensorrt inference needs 1d memory with size `3xWidthxHeight`, 

One solution could be to allocate a gpu memory outside of VPF and use `cuMemcpy2DAsync` with appropriate parameters to populate the memory.

Had it been implemented in VPF to download the 1d gpu memory (`Surface`) as you do for `CudaDownloadSurface` to download host memory, it could have been easier to use the `GpuMem()` directly to the downstream inference application.

**Comment by rarzumanyan** [comment] 2021-03-18 18:32
@vtpl1 

Thanks for the explanation.
>but the application like tensorrt inference needs 1d memory with size `3xWidthxHeight`

Python bindings for TensorRT use non-pitched 1D CUDA memory allocation?

**Comment by lferraz** [comment] 2021-04-30 15:32
@rarzumanyan , correct me if I am wrong. 
is this related with the new Import/Export feature?

**Comment by rarzumanyan** [comment] 2021-04-30 16:09
I guess there's some intersection between those.

**Comment by rarzumanyan** [comment] 2021-05-17 06:28
No updates from issue originator, closing this issue as resolved.
Please reopen in case it still reproduces.

**Closed by rarzumanyan** 2021-05-17 06:28 UTC
