### ISSUE TITLE
Unexpected seeking behavior at the beginning of a video

### ISSUE THREAD

**Issue by SiftingSands** [NVIDIA/VideoProcessingFramework#218] opened 2021-06-04 21:47 UTC
**Describe the bug**
Seeking seems to start at the wrong frame for just the beginning of the video. Maybe related to the negative dts? Probably not a huge deal operationally, but thought I would add this observation anyway.

**To Reproduce**
Run `SampleDecode.py` with `self.seek_mode = nvc.SeekMode.EXACT_FRAME` and verbose logs on. Using the `STANDALONE` decoder as configured by default. Test video : https://github.com/NVIDIA/DALI_extra/blob/main/db/video/test_label.mp4

Results with varying `sk_frm` and printing only the first 5 for brevity.

`self.sk_frm = -1`: (I thought this was deprecated from https://github.com/NVIDIA/VideoProcessingFramework/issues/178#issue-839705819, but it still works.)
```
Decoding on GPU 0
frame pts (decode order)      : 0
frame dts (decode order)      : -1024
frame pos (decode order)      : 48
frame duration (decode order) : 512

frame pts (decode order)      : 2048
frame dts (decode order)      : -512
frame pos (decode order)      : 1669
frame duration (decode order) : 512

frame pts (decode order)      : 1024
frame dts (decode order)      : 0
frame pos (decode order)      : 1954
frame duration (decode order) : 512

frame pts (decode order)      : 512
frame dts (decode order)      : 512
frame pos (decode order)      : 2121
frame duration (decode order) : 512

frame pts (decode order)      : 1536
frame dts (decode order)      : 1024
frame pos (decode order)      : 2278
frame duration (decode order) : 512
```

`self.sk_frm = 0`: Shouldn't this start at pts=0?
```
Decoding on GPU 0
Seeking for the frame  0
We are at frame with pts 1024
frame pts (decode order)      : 1024
frame dts (decode order)      : 0
frame pos (decode order)      : 1954
frame duration (decode order) : 512

frame pts (decode order)      : 512
frame dts (decode order)      : 512
frame pos (decode order)      : 2121
frame duration (decode order) : 512

frame pts (decode order)      : 1536
frame dts (decode order)      : 1024
frame pos (decode order)      : 2278
frame duration (decode order) : 512

frame pts (decode order)      : 4096
frame dts (decode order)      : 1536
frame pos (decode order)      : 2456
frame duration (decode order) : 512

frame pts (decode order)      : 3072
frame dts (decode order)      : 2048
frame pos (decode order)      : 2746
frame duration (decode order) : 512
```

`self.sk_frm = 1`: This starts **before** `sk_frm=0`?
```
Decoding on GPU 0
Seeking for the frame  1
We are at frame with pts 512
frame pts (decode order)      : 512
frame dts (decode order)      : 512
frame pos (decode order)      : 2121
frame duration (decode order) : 512

frame pts (decode order)      : 1536
frame dts (decode order)      : 1024
frame pos (decode order)      : 2278
frame duration (decode order) : 512

frame pts (decode order)      : 4096
frame dts (decode order)      : 1536
frame pos (decode order)      : 2456
frame duration (decode order) : 512

frame pts (decode order)      : 3072
frame dts (decode order)      : 2048
frame pos (decode order)      : 2746
frame duration (decode order) : 512

frame pts (decode order)      : 2560
frame dts (decode order)      : 2560
frame pos (decode order)      : 2961
frame duration (decode order) : 512
```
`self.sk_frm = 2`:
```
Decoding on GPU 0
Seeking for the frame  2
We are at frame with pts 1536
frame pts (decode order)      : 1536
frame dts (decode order)      : 1024
frame pos (decode order)      : 2278
frame duration (decode order) : 512

frame pts (decode order)      : 4096
frame dts (decode order)      : 1536
frame pos (decode order)      : 2456
frame duration (decode order) : 512

frame pts (decode order)      : 3072
frame dts (decode order)      : 2048
frame pos (decode order)      : 2746
frame duration (decode order) : 512

frame pts (decode order)      : 2560
frame dts (decode order)      : 2560
frame pos (decode order)      : 2961
frame duration (decode order) : 512

frame pts (decode order)      : 3584
frame dts (decode order)      : 3072
frame pos (decode order)      : 3124
frame duration (decode order) : 512
```
```
Decoding on GPU 0
Seeking for the frame  5
We are at frame with pts 2560
frame pts (decode order)      : 2560
frame dts (decode order)      : 2560
frame pos (decode order)      : 2961
frame duration (decode order) : 512

frame pts (decode order)      : 3584
frame dts (decode order)      : 3072
frame pos (decode order)      : 3124
frame duration (decode order) : 512

frame pts (decode order)      : 6144
frame dts (decode order)      : 3584
frame pos (decode order)      : 3274
frame duration (decode order) : 512

frame pts (decode order)      : 5120
frame dts (decode order)      : 4096
frame pos (decode order)      : 3639
frame duration (decode order) : 512

frame pts (decode order)      : 4608
frame dts (decode order)      : 4608
frame pos (decode order)      : 3816
frame duration (decode order) : 512
```

```
Decoding on GPU 0
Seeking for the frame  10
We are at frame with pts 5632
frame pts (decode order)      : 5632
frame dts (decode order)      : 5120
frame pos (decode order)      : 3961
frame duration (decode order) : 512

frame pts (decode order)      : 8192
frame dts (decode order)      : 5632
frame pos (decode order)      : 4121
frame duration (decode order) : 512

frame pts (decode order)      : 7168
frame dts (decode order)      : 6144
frame pos (decode order)      : 4411
frame duration (decode order) : 512

frame pts (decode order)      : 6656
frame dts (decode order)      : 6656
frame pos (decode order)      : 4615
frame duration (decode order) : 512

frame pts (decode order)      : 7680
frame dts (decode order)      : 7168
frame pos (decode order)      : 4762
frame duration (decode order) : 512
```
I checked a few more after `sk_frm=10`, and the seeked frame aligns with `pts` as expected.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nvidia driver version 440.33.01
 - CUDA Version 10.2
 - Video Codec SDK Version Video_Codec_SDK_10.0.26
 - Python Version 3.6.9

**Comment by rarzumanyan** [comment] 2021-06-07 08:19
Hi @SiftingSands 

The issue description is quite large so let me address it step by step.
Please reply if I'm missing something.

>self.sk_frm = -1: (I thought this was deprecated from #178 (comment), but it still works.)

Negative seek frame number is checked in `SeekContext` constructor:
https://github.com/NVIDIA/VideoProcessingFramework/blob/0b9db50713e218ec06b043e958ea30a9c05ac0f7/PyNvCodec/TC/inc/FFmpegDemuxer.h#L70-L84

But since it's a plain `struct` you can assign negative frame number later. I'll add the check here before the seek procedure starts:
https://github.com/NVIDIA/VideoProcessingFramework/blob/0b9db50713e218ec06b043e958ea30a9c05ac0f7/PyNvCodec/src/PyNvCodec.cpp#L765

Regarding the overall seek performance: please take note that demuxer operates in decode mode, not display mode. So frame dts numbers are actually increasing with step equal of `512`. Unlike that, decoder operates in display mode, hence it shall output frames with pts numbers increasing.

**Comment by SiftingSands** [comment] 2021-06-07 14:05
Hi @rarzumanyan,

My apologies, I just realized that I forgot to account for https://github.com/NVIDIA/VideoProcessingFramework/blob/0b9db50713e218ec06b043e958ea30a9c05ac0f7/SampleDecode.py#L213 when stating that negative seeks were not deprecated. So, the previous results for `sk_frm = -1` correspond to no seeking performed in `SampleDecode.py`.

Bypassing that check gives (without checking out https://github.com/NVIDIA/VideoProcessingFramework/commit/789b13df6ac00127993cfcd0f3d212337089e55d):
```
Seeking for the frame  -1
Negative frame number is not allowed
```

I'm still unclear on why seeking to frame 0 and not seeking at all has a 1024 dts offset. At first glance, it's due to `pts=0` corresponding to `dts=-1024` and seeking to frame 0 skips these negative dts frames? I could try to save the frames to disk and visually inspect them, but I thought I would ask first.

**Comment by rarzumanyan** [comment] 2021-06-07 16:07
Hi @SiftingSands 

>why seeking to frame 0 and not seeking at all has a 1024 dts offset

Demuxer extracts encoded video frames in decode order which may be different from display order. In contrast to that, decoder returns frames in display order.

My advice is just to use `BUILTIN` mode if you're dealing with local files and seek via decoder's interface. It does return video frames in display order and you don't have to mess up with `pts` and `dts` timestamps (which BTW aren't the part of H.264 and H.265 standards!). 

This causes a confusion what timestamp to use when you seek for a frame. FFMpeg seek API accepts just a frame's timestamp:
https://github.com/NVIDIA/VideoProcessingFramework/blob/0b9db50713e218ec06b043e958ea30a9c05ac0f7/PyNvCodec/TC/src/FFmpegDemuxer.cpp#L234-L246

Since demuxer doesn't know a thing about decoder's presence the seek is done using comparison of a target frame `dts` and current frame `dts`.

Unlike that, decoder knows presentation timestamp (the time video frame is presented to viewer) for sure so it seeks for a video frame "as normal human may expect". If you ask decoder frame number `X` it will return you exactly the `X`th frame in display order which you can simply check with any raw video player.

**Comment by SiftingSands** [comment] 2021-06-07 20:35
Thanks for the detailed responses as always! I was testing out the `BUILTIN` module as well, and I agree that it has a more intuitive seek behavior. 

Results to contrast the original observations in case other VPF users come across similar concerns. (Had to set `seek_mode = nvc.SeekMode.PREV_KEY_FRAME` b/c `EXACT_FRAME` is unsupported for `BUILTIN`)

no seeking is performed:
```
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 512
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 1024
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```
matches the case without seeking :
```
Seeking for the frame  0
frame pts (display order)      : 0
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 512
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 1024
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```
Starts at the next frame as expected:
```
Seeking for the frame  1
frame pts (display order)      : 512
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 1024
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 1536
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```

I did have one more observation to add when testing on a YouTube video, https://drive.google.com/file/d/1JAdvkXCsIk_Nnw9-XVm_q9eNN25oOTq0/view?usp=sharing. It looks like frame 461 is an I-frame, but seeking to that frame goes to frame 512 instead?

```
Seeking for the frame  460
frame pts (display order)      : 235520
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```
```
Seeking for the frame  461
frame pts (display order)      : 262144
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```
Seeks >461 and <513 keep starting at frame 512 as well:
```
Seeking for the frame  465
frame pts (display order)      : 262144
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```

```
Seeking for the frame  513
frame pts (display order)      : 262656
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0
```
I was able to download the frames to disk, and the reported `pts` seems consistent between seeks and images don't show artifacts. I first saw this brought up when testing out DALI (see https://github.com/NVIDIA/DALI/issues/2919 and I jumped the gun on reporting full success), and Janusz concluded that it was a corrupted frame. This is somewhat of a silent failure if verbose logs aren't checked, but I understand it might be the user's responsibility for data integrity. Regardless, leaving this here if you wanted to take a look, and close this issue if deemed out-of-scope.

**Comment by rarzumanyan** [comment] 2021-06-08 12:19
Hi @SiftingSands 

In your video stream frame 461 in marked as H.264 recovery point.
Hence demuxer struggles to use it for seek as it doesn't see frame 461 as key frame so it seeks for frame 512 as "true" key frame:
![EmotionalInterview](https://user-images.githubusercontent.com/45193474/121183087-61564900-c86c-11eb-8f93-203d534d65d5.png)

This is interesting stuff, requires more investigation!

**Comment by rarzumanyan** [comment] 2021-06-08 13:45
Hi @SiftingSands 
More updates on this case:

Demuxer actually seeks for the frame `461` as you ask it to seek.
The issue lies on decoder side - it struggles to return decoded frames between recovery point (frame `461`) and next key frame (`512`).
I've modified the code slightly to see how many frames are kicked off to HW before we get a frame ready for display:
```cpp
Surface *PyNvDecoder::getDecodedSurface(NvdecDecodeFrame *decoder,
                                        DemuxFrame *demuxer,
                                        SeekContext &seek_ctx,
                                        bool needSEI) {
  Surface *surface = nullptr;
  auto num_runs = 0U;
  do {
    auto elementaryVideo = getElementaryVideo(demuxer, seek_ctx, needSEI);
    auto pktData = (Buffer *)demuxer->GetOutput(3U);

    decoder->SetInput(elementaryVideo, 0U);
    decoder->SetInput(pktData, 1U);
    if (TASK_EXEC_FAIL == decoder->Execute()) {
      break;
    }

    surface = (Surface *)decoder->GetOutput(0U);
    num_runs++;
  } while (!surface);

  cout << num_runs
       << " frames kicked off for decoding before we got a frame ready for "
          "display."
       << endl;
  return surface;
};
```

As I seek for frame `461` this is the output I get:
```
Decoding on GPU 0
Seeking for the frame  461
55 frames kicked off for decoding before we got a frame ready for display.
```
Decoder can't get frames between `461` and `512`, then it faces a usual delay of 4 frames.
I assume there are some specific actions needed to be taken to maintain recovery point SEI on Nvdec side. 
I'll update you later as I find something on this topic.

**Comment by rarzumanyan** [comment] 2021-06-09 17:06
@SiftingSands 

One more update:
Compressed frames between `461` and `512` are demuxed from container and sent to decoder although `HandlePictureDecode()` and `HandlePictureDisplay()` parser callbacks are never called on them. So I assume it's Annex.B parser bug which makes it skip all the frames between `461` and `512`. Probably parser expects frame `461` to be IDR frame which it's not (it has sclie header type of `I` and not `I, IDR`).

I'll inform our Video Codec SDK team about this parser behavior. As soon as I get word back from them I'll update you in this thread.

**Comment by rarzumanyan** [comment] 2021-06-22 11:32
Hi @SiftingSands 
I've got a response from our VC SDK team, and it makes tons of sense ;)

It turns that in the test script, the first actual operation on bitstream is random access caused by `Seek()`.
The demuxer returns the exact frame `461` we're asking it for but Nvdec can't decode it because there are no SPS and PPS NALU prepending that frame. 

So decoder isn't fully configured at the moment (it doesn't know essential bitstream parameters such as resolution, profile, level etc.) and it skips all the frames up to `512` because there are SPS & PPS NALU prepending this frame.

Could you please run the same testing script with one change to it: please decode at least 1 video frame before seeking to frame `461` and confirm that the issue no longer reproduces?

**Comment by SiftingSands** [comment] 2021-06-22 17:18
Hi @rarzumanyan 

As suggested, I decode one video frame before seeking to frame 461. However, I still observe the same behavior where it produces frame 512 instead of 461.

Here's the code that I'm using, which is based on https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecode.py with minor changes. I also tried seeking to and decoding other frames < 461 instead of the first one, but the results were the same.

Output:
```
Decoding on GPU 0
Decoding first frame for initialization
frame pts (display order)      : 0
Seeking for the frame  461
frame pts (display order)      : 262144
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 262656
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 263168
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 263680
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 264192
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 264704
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 265216
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 265728
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 266240
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

frame pts (display order)      : 266752
frame dts (display order)      : 0
frame pos (display order)      : 0
frame duration (display order) : 0

```

Test script:
```
import sys
import os
sys.path.append("/app")
if os.name == 'nt':
    # Add CUDA_PATH env variable
    cuda_path = os.environ["CUDA_PATH"]
    if cuda_path:
        os.add_dll_directory(cuda_path)
    else:
        print("CUDA_PATH environment variable is not set.", file = sys.stderr)
        print("Can't set CUDA DLLs search path.", file = sys.stderr)
        exit(1)

    # Add PATH as well for minor CUDA releases
    sys_path = os.environ["PATH"]
    if sys_path:
        paths = sys_path.split(';')
        for path in paths:
            if os.path.isdir(path):
                os.add_dll_directory(path)
    else:
        print("PATH environment variable is not set.", file = sys.stderr)
        exit(1)

import PyNvCodec as nvc
from enum import Enum
import numpy as np

if os.name == 'nt':
    # Add CUDA_PATH env variable
    cuda_path = os.environ["CUDA_PATH"]
    if cuda_path:
        os.add_dll_directory(cuda_path)
    else:
        print("CUDA_PATH environment variable is not set.", file = sys.stderr)
        print("Can't set CUDA DLLs search path.", file = sys.stderr)
        exit(1)

    # Add PATH as well for minor CUDA releases
    sys_path = os.environ["PATH"]
    if sys_path:
        paths = sys_path.split(';')
        for path in paths:
            if os.path.isdir(path):
                os.add_dll_directory(path)
    else:
        print("PATH environment variable is not set.", file = sys.stderr)
        exit(1)

import PyNvCodec as nvc
from enum import Enum
import numpy as np

class InitMode(Enum):
    # Decoder will be created with built-in demuxer.
    BUILTIN = 0,
    # Decoder will be created with standalone FFmpeg VPF demuxer.
    STANDALONE = 1

class DecodeStatus(Enum):
    # Decoding error.
    DEC_ERR = 0,
    # Frame was submitted to decoder.
    # No frames are ready for display yet.
    DEC_SUBM = 1,
    # Frame was submitted to decoder.
    # There's a frame ready for display.
    DEC_READY = 2

class NvDecoder:
    def __init__(self, gpu_id: int, enc_file: str, dec_file: str, 
                 dmx_mode=InitMode.STANDALONE):
        # Save mode, we will need this later
        self.init_mode = dmx_mode

        if self.init_mode == InitMode.STANDALONE:
            # Initialize standalone demuxer.
            self.nv_dmx = nvc.PyFFmpegDemuxer(enc_file)
            # Initialize decoder.
            self.nv_dec = nvc.PyNvDecoder(self.nv_dmx.Width(), self.nv_dmx.Height(), 
                                          self.nv_dmx.Format(), self.nv_dmx.Codec(), 
                                          gpu_id)
        else:
            # Initialize decoder with built-in demuxer.
            self.nv_dmx = None
            self.nv_dec = nvc.PyNvDecoder(enc_file, gpu_id)

        # Frame to seek to next time decoding function is called.
        # Negative values means 'don't use seek'.  Non-negative values mean
        # seek frame number.
        self.sk_frm = 461 #int(-1)
        # Total amount of decoded frames
        self.num_frames_decoded = int(0)
        # Numpy array to store decoded frames pixels
        self.frame_nv12 = np.ndarray(shape=(0), dtype=np.uint8)
        # Output file
        #self.out_file = open(dec_file, "wb")
        # Encoded video packet
        self.packet = np.ndarray(shape=(0), dtype=np.uint8)
        # Encoded packet data
        self.packet_data = nvc.PacketData()
        # Seek mode
        self.seek_mode = nvc.SeekMode.PREV_KEY_FRAME #EXACT_FRAME
        
    # Returns decoder creation mode
    def mode(self) -> InitMode:
        return self.init_mode

    # Returns video width in pixels
    def width(self) -> int:
        if self.mode() == InitMode.STANDALONE:
            return self.nv_dmx.Width()
        else:
            return self.nv_dec.Width()

    # Returns video height in pixels
    def height(self) -> int:
        if self.mode() == InitMode.STANDALONE:
            return self.nv_dmx.Height()
        else:
            return self.nv_dec.Height()

    # Returns number of decoded frames.
    def dec_frames(self) -> int:
        return self.num_frames_decoded

    def framerate(self) -> int:
        if self.mode() == InitMode.STANDALONE:
            return self.nv_dmx.Framerate()
        else:
            return self.nv_dec.Framerate()

    # Returns number of frames in video.
    def stream_num_frames(self) -> int:
        if self.mode() == InitMode.STANDALONE:
            return self.nv_dmx.Numframes()
        else:
            return self.nv_dec.Numframes()

    # Seek for particular frame number.
    def seek(self, seek_frame: int, seek_mode: nvc.SeekMode) -> None:
            # Next time we decode frame decoder will seek for this frame first.
            self.sk_frm = seek_frame
            self.seek_mode = seek_mode

    def decode_frame_standalone(self, verbose=False) -> DecodeStatus:
        status = DecodeStatus.DEC_ERR

        try:
            # Check if we need to seek first.
            if self.sk_frm >= 0:
                print('Seeking for the frame ', str(self.sk_frm))
                seek_ctx = nvc.SeekContext(int(self.sk_frm), self.seek_mode)
                self.sk_frm = -1

                if not self.nv_dmx.Seek(seek_ctx, self.packet):
                    return status

                print('We are at frame with pts', str(seek_ctx.out_frame_pts))
            # Otherwise we just demux next packet.
            elif not self.nv_dmx.DemuxSinglePacket(self.packet):
                print('Demuxed')
                return status
            print('Decoded')
            # Send encoded packet to Nvdec.
            # Nvdec is async so it may not return decoded frame immediately.
            frame_ready = self.nv_dec.DecodeFrameFromPacket(self.frame_nv12, self.packet)
            if frame_ready:
                status = DecodeStatus.DEC_READY
            else:
                status = DecodeStatus.DEC_SUBM
            self.num_frames_decoded += 1
            # Get last demuxed packet data.
            # It stores info such as pts, duration etc.
            self.nv_dmx.LastPacketData(self.packet_data)

            #if verbose:
            print("frame pts (decode order)      :", self.packet_data.pts)
            print("frame dts (decode order)      :", self.packet_data.dts)
            print("frame pos (decode order)      :", self.packet_data.pos)
            print("frame duration (decode order) :", self.packet_data.duration)
            print("")
        except Exception as e:
                print(getattr(e, 'message', str(e)))

        return status

    def decode_frame_builtin(self, verbose=False) -> DecodeStatus:
        status = DecodeStatus.DEC_ERR

        try:
            frame_ready = False
            frame_cnt_inc = 0

            if self.sk_frm >= 0:
                print(f'Decoding first frame for initialization')
                frame_ready = self.nv_dec.DecodeSingleFrame(self.frame_nv12, self.packet_data)
                print("frame pts (display order)      :", self.packet_data.pts)
                
                print('Seeking for the frame ', str(self.sk_frm))
                seek_ctx = nvc.SeekContext(int(self.sk_frm), self.seek_mode)
                self.sk_frm = -1

                frame_ready = self.nv_dec.DecodeSingleFrame(self.frame_nv12, 
                                                            seek_ctx, self.packet_data)
                frame_cnt_inc = seek_ctx.num_frames_decoded
            else:
                frame_ready = self.nv_dec.DecodeSingleFrame(self.frame_nv12, self.packet_data)
                frame_cnt_inc = 1

            # Nvdec is sync in this mode so if frame isn't returned it means
            # EOF or error.
            if frame_ready:
                self.num_frames_decoded += frame_cnt_inc
                status = DecodeStatus.DEC_READY
            else:
                return status

            if verbose:
                print("frame pts (display order)      :", self.packet_data.pts)
                print("frame dts (display order)      :", self.packet_data.dts)
                print("frame pos (display order)      :", self.packet_data.pos)
                print("frame duration (display order) :", self.packet_data.duration)
                print("")

        except Exception as e:
                print(getattr(e, 'message', str(e)))

        return status

    # Decode single video frame
    def decode_frame(self, verbose=False) -> DecodeStatus:
        if self.mode() == InitMode.STANDALONE:
            return self.decode_frame_standalone(verbose)
        else:
            return self.decode_frame_builtin(verbose)

    # Send empty packet to decoder to flush decoded frames queue.
    def flush_frame(self, verbose=False) -> None:
        ret = self.nv_dec.FlushSingleFrame(self.frame_nv12)
        if ret:
            self.num_frames_decoded += 1

        return ret

    # Write current video frame to output file.
    def dump_frame(self) -> None:
        bits = bytearray(self.frame_nv12)
        self.out_file.write(bits)

    # Decode all available video frames and write them to output file.
    def decode(self, frames_to_decode=-1, verbose=False) -> None:
        # Main decoding cycle
        while (self.dec_frames() < frames_to_decode) if (frames_to_decode > 0) else True:
            status = self.decode_frame(verbose)
            if status == DecodeStatus.DEC_ERR:
                break
            elif self.num_frames_decoded >= 10:
                break
        #     elif status == DecodeStatus.DEC_READY:
        #         self.dump_frame()

        # # Check if we need flush the decoder
        # need_flush = (self.dec_frames() < frames_to_decode) if (frames_to_decode > 0) else True

        # # Flush decoded frames queue.
        # # This is needed only if decoder is initialized without built-in
        # # demuxer and we're not limited in amount of frames to decode.
        # while need_flush and (self.mode() == InitMode.STANDALONE):
        #     if not self.flush_frame(verbose):
        #         break
        #     else:
        #         self.dump_frame()

if __name__ == "__main__":

    # print("This sample decodes input video to raw NV12 file on given GPU.")
    # print("Usage: SampleDecode.py $gpu_id $input_file $output_file.")

    # if(len(sys.argv) < 4):
    #     print("Provide gpu ID, path to input and output files")
    #     exit(1)

    gpu_id = 0 #int(sys.argv[1])
    enc_filePath = './Eartha Kitt - Emotional interview.mp4' #sys.argv[2]
    dec_filePath = None #sys.argv[3]
    
    dec = NvDecoder(gpu_id, enc_filePath, dec_filePath, InitMode.BUILTIN)
    dec.decode(verbose=True)

    exit(0)

```

**Comment by rarzumanyan** [comment] 2021-07-15 12:53
Hi  @SiftingSands 

I've removed the decoder flush to prevent SPS & PPS preemtion.
On my machine it now seeks to the frame 461 after the decoder is initialized. Please check out if issue is solved.

**Comment by SiftingSands** [comment] 2021-07-16 15:49
@rarzumanyan Confirming that VPF successfully seeks to frame `461` after initializing the decoder by a call to `DecodeSingleFrame` without a seek context. During this test, I also decoded the next few frames and saved them to disk. Unfortunately, it appears that frames 464 and 465 are corrupted, which I did not observe by either extracting frames with FFMPEG or decoding without seeks.
464:
![image_464](https://user-images.githubusercontent.com/43226539/125974399-7e29fc27-da20-4c6a-aa9c-37cfb29d7fec.png)
465:
![image_465](https://user-images.githubusercontent.com/43226539/125974416-9cd7267b-80e9-408a-8e9a-a4cc98e977ee.png)

Let me know if you need more info from me, especially if it's not reproducible on your end.

**Comment by rarzumanyan** [comment] 2021-07-21 15:23
Hi @SiftingSands 

I confirm that the issue reproduces on my end.
Frankly I'm running out of ideas what may be the reason for such behavior. As I have something I'll update you in this thread.

**Comment by SiftingSands** [comment] 2021-07-21 15:43
@rarzumanyan No worries, I appreciate all the followup so far! My hacky solution is just to check if the received timestamp and if it doesn't match the seek time, then I just decode from the beginning until I reach the desired timestamp.

**Comment by ValZapod** [comment] 2021-11-22 05:17
> doesn't see frame 461 as key frame so it seeks for frame 512 as "true" key frame:

But recovery point is a key frame: https://github.com/FFmpeg/FFmpeg/blob/98aec8c1b864e44636c0fabdaff3494d2051fda3/libavcodec/h264_slice.c#L2254

**Comment by rarzumanyan** [comment] 2021-11-22 09:40
@ValZapod @SiftingSands 

This is caused by the Video Codec SDK implementation which so far can only do random access to closest IDR I frame in the past, then to decode frames until the actual seek frame is reached. This is done in such a way because IDR I frame is to be preceded by SPS and PPS NALU which may cause decoder reconfigure (unlike non-IDR I frame).

In this video, Recovery Point is non-IDR I frame, hence the behavior mismatch between FFMpeg demuxer which can jump to non-IDR I frame and decoder which can't. If random access to non-IDR I frame is added to driver, I'll re-open this issue and will ask originator to confirm. 

Meanwhile I'm closing this issue because the requested feature isn't supported yet.

**Closed by rarzumanyan** 2021-11-22 09:40 UTC
