### ISSUE TITLE
PyNvCodec.HwResetException: HW reset

### ISSUE THREAD

**Issue by XZG-0457** [NVIDIA/VideoProcessingFramework#83] opened 2020-07-21 03:24 UTC
When I decoded the rtsp stream, I found that running to `rawSurface = nvDec.DecodeSingleSurface()` there is a high probability that an error will occur:

```python
Decode Error occurred for picture 25
Exception thrown during decoding process: HW decoder faced error. Re-create instance.
HW decoder will be reset.
HW decoder reset time: 16 milliseconds
Traceback (most recent call last):
   File "/FrameManager.py", line 288, in produce_frame
     rawSurface = nvDec.DecodeSingleSurface()
PyNvCodec.HwResetException: HW reset
exract video 24 error:HwResetException('HW reset',)
```

I want to ask why this problem occurs. I have also seen this in your source code:
![image](https://user-images.githubusercontent.com/43441239/88009162-69b67000-cb44-11ea-8195-d6d8d0e5075c.png)

**Comment by rarzumanyan** [comment] 2020-07-21 05:59
Hi @XZG-0457 
This issue is duplicate of https://github.com/NVIDIA/VideoProcessingFramework/issues/47 and https://github.com/NVIDIA/VideoProcessingFramework/issues/67

**Closed by rarzumanyan** 2020-07-21 05:59 UTC
