### ISSUE TITLE
PyNvCodec/TC/CMakeFiles/TC.dir/build.make:75: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o' failed

### ISSUE THREAD

**Issue by pureloveljc** [NVIDIA/VideoProcessingFramework#65] opened 2020-06-17 11:47 UTC
I can't compile the video processing framework according to your tutorial

PyNvCodec/TC/CMakeFiles/TC.dir/build.make:75: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o' failed
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o] Error 1
CMakeFiles/Makefile2:165: recipe for target 'PyNvCodec/TC/CMakeFiles/TC.dir/all' failed
make[1]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pureloveljc** [comment] 2020-06-17 11:47
@swarren

**Comment by pureloveljc** [comment] 2020-06-17 11:50
@aaronp24 @ferdnyc @lukeyeager 
thank you  very much

**Comment by rarzumanyan** [comment] 2020-06-17 11:56
Hi @pureloveljc 
Is this solved?

**Comment by swarren** [comment] 2020-06-17 16:08
Please don't @ mention individual users. I don't work on this project, just admin some git repos. Thanks.

**Comment by pureloveljc** [comment] 2020-06-18 01:36
This is still the problem.
my driver 430.30

**Comment by pureloveljc** [comment] 2020-06-18 02:17
ffmpeg -y -i v_test.avi -vcodec h264 -strict -2 v_test.mp4

Unknown encoder ‘h264’  

Whether ffmpeg compilation error will cause VPF compilation error

**Comment by pureloveljc** [comment] 2020-06-18 05:49
My environment
 NVIDIA-SMI 430.34       Driver Version: 430.34       CUDA Version: 10.1     |

**Comment by rarzumanyan** [comment] 2020-06-18 13:08
Hi,

Sorry, I don't get it. If you have compilation issues, please upload the compiler error message.
I see that you can't compile `Tasks.cpp` file but don't know what's happening exactly.

>`ffmpeg -y -i v_test.avi -vcodec h264 -strict -2 v_test.mp4`
`Unknown encoder ‘h264’`

Not sure if this is relevant to VPF, it only uses ffmpeg C API for demuxing.

**Comment by pureloveljc** [comment] 2020-06-19 03:22
Hi @rarzumanyan   ,  
![image](https://user-images.githubusercontent.com/32063794/85093435-dc1ef200-b21e-11ea-987c-c75dcf249361.png)
 
Cmake is successful, but it reminds me libnvcuvid.so .1 => not found

My environment is running in docker. Is there any problem with VPF running in docker?

**Comment by pureloveljc** [comment] 2020-06-19 05:57
I copy from this machine libnvcuvid.so . 1, it seems to be solved, but run Python 3/ SampleDecode.py

Error occurred, memoryerror: STD:: bad_ Alloc, but I still have a lot of memory

![image](https://user-images.githubusercontent.com/32063794/85101353-d0d6c100-b234-11ea-9715-9bac9fb24b8e.png)

**Comment by rarzumanyan** [comment] 2020-06-19 06:21
You need to choose ‘video’ capability of the GPU driver when running the image, then cuvid library will be visible from within container.

I’m not aware of any specific VPF issues if it’s running within container.

Please use the ‘video’ driver capability and update me if it solves your problem.

**Comment by pureloveljc** [comment] 2020-06-19 07:49
docker run --runtime=nvidia -d -e NVIDIA_VISIBLE_DEVICES=0,1 -e NVIDIA_DRIVER_CAPABILITIES=video,compute,utility    加上这个 就 成功解决了，但是run  python3  ./SampleDecode.py  依然有MemoryError: std::bad_alloc的 错误

**Comment by pureloveljc** [comment] 2020-06-19 07:50
docker run --runtime=nvidia -d -e NVIDIA_ VISIBLE_ DEVICES=0,1 -e NVIDIA_ DRIVER_ Capabilities = video, compute, utility plus this one will solve it successfully, but run Python 3/ SampleDecode.py There are still memoryerrors: STD:: bad_ Alloc error

**Comment by rarzumanyan** [comment] 2020-06-19 09:10
Ok, will be needing you help to debug this.
I've never faced this type of exception before. Looks like some of the STL containers fails to allocate the memory. 

Please change the content of PyNvCodec.cpp at line 406 with the snippet below:

```cpp
  PyNvDecoder(const string &pathToFile, int gpuOrdinal,
              const map<string, string> &ffmpeg_options) {
    if (gpuOrdinal < 0 || gpuOrdinal >= CudaResMgr::Instance().GetNumGpus()) {
      gpuOrdinal = 0U;
    }
    gpuId = gpuOrdinal;
    cout << "Decoding on GPU " << gpuId << endl;

    vector<const char *> options;
    for (auto &pair : ffmpeg_options) {
      options.push_back(pair.first.c_str());
      options.push_back(pair.second.c_str());
    }
    cout << __LINE__ << endl;

    upDemuxer.reset(
        DemuxFrame::Make(pathToFile.c_str(), options.data(), options.size()));
    cout << __LINE__ << endl;

    MuxingParams params;
    upDemuxer->GetParams(params);
    cout << __LINE__ << endl;

    upDecoder.reset(NvdecDecodeFrame::Make(
        CudaResMgr::Instance().GetStream(gpuId),
        CudaResMgr::Instance().GetCtx(gpuId), params.videoContext.codec,
        poolFrameSize, params.videoContext.width, params.videoContext.height));
    cout << __LINE__ << endl;
  }
```

It will give a generic overview of where the exception is thrown;

**Comment by pureloveljc** [comment] 2020-06-19 09:28
![image](https://user-images.githubusercontent.com/32063794/85117856-148bf380-b252-11ea-9984-ecee75ecd1d6.png)
Hard work, brother

**Comment by rarzumanyan** [comment] 2020-06-19 10:59
Just to make sure, you launch python script with cmd line as follows ?
```bash
python3 SampleDecode.py
```

**Comment by rarzumanyan** [comment] 2020-06-19 11:07
Just to make sure, can you run the decode sample with local video file as input or using publicly available rtsp stream like it's described here https://github.com/NVIDIA/VideoProcessingFramework/issues/47#issuecomment-629985077 ?

**Comment by pureloveljc** [comment] 2020-06-22 02:52
I tried to install VPF on the host, and it succeeded without using the docker container

**Comment by rarzumanyan** [comment] 2020-06-22 06:16
So the issue is Docker-specific and doesn't reproduce on host machine?

**Comment by pureloveljc** [comment] 2020-06-22 06:20
So far, it's like this~

**Comment by rarzumanyan** [comment] 2020-07-21 06:07
Closing the issue as fixed.
Please reopen in case it's still relevant.

**Closed by rarzumanyan** 2020-07-21 06:07 UTC
